### ISSUE TITLE
BASH Prompt does not display root user prompt or color under certain circumstances

### ISSUE THREAD

**Issue by dcharlespyle** [folkswithhats/fedy#159]
Under certain circumstances, the root user prompt "#" isn't displayed after running Fedy to add colors to the prompt.  Try sudo su, sudo -s and a few others, and the prompt isn't displayed correctly, along with no change in color for the root user as used to be the case.  I found the cause of the error, which was in the /etc/profile.d/color_prompt.sh file, as follows:

    if [[ $USER = "root" ]]; then

This does not work right if any aspect of the elevating user remains in the environment.  Compare with su - in a terminal window with the results of the above, which replaces the previous environment with the actual root environment.  What works better is the following replacing that above line:

    if [[ $(id -u) -eq 0 ]]; then

That change never fails to produce the proper prompt and red coloration for the root user on my Fedora 21 system.

**Comment by Rohan62442** [comment]
Instead of using `$(id -u)` you should go with the `$EUID` variable. @dcharlespyle can you put in a pull request?
