### ISSUE TITLE
Suggestion: Please add Pharlap

### ISSUE THREAD

**Issue by geckolinux** [folkswithhats/fedy#176]
Hello,

First of all, allow me to congratulate you. Fedy makes Fedora a LOT more appealing to mere mortals. My sincere thanks for creating it!

Would it be possible to add Pharlap as an option to Fedy, to make installing proprietary drivers easier?
- https://archive.kororaproject.org/wp-content/uploads/2013/12/pharlap.jpg
- https://github.com/kororaproject/kp-pharlap

Thanks a lot!

**Comment by satya164** [comment]
Cool. Will check it out.

**Comment by sb56637** [comment]
Thanks a lot @satya164 ! It should be easy to add, you could probably just pull it from the Korora servers:

http://dl.kororaproject.org/pub/korora/releases/21/x86_64/ (there's a few different Pharlap RPMs inside)

**Comment by satya164** [comment]
I think it'll be best ask the maintainers and add it to Ozon OS repo, so we will be able to provide updates without having to add the Korora repo. It'll take some time, but we'll do it. Thanks a lot :D

**Comment by sb56637** [comment]
Great, thanks!

**Comment by PhnxRbrn** [comment]
Has there been any news on adding this to the ozon repo?

**Comment by satya164** [comment]
@PhnxRbrn no, we've not yet discussed.

**Comment by Abhinav1217** [comment]
The devs have stopped working on Pharlap and hence this discussion is obsolete.
