### ISSUE TITLE
Require some more softwares

### ISSUE THREAD

**Issue by gauravdighe** [folkswithhats/fedy#179]
Previous version of Fedy had more softwares.
Anyways I would love to see some more softwares like handbrake-gtk, conky, coverglobus, some more very attractive themes and icons

**Comment by testman42** [comment]
In fact, why not make Fedy distro-agnostic and contact Ninite dudes and propose merge, to make universal popular-software-installer for every OS.

**Comment by satya164** [comment]
@testman42 Fedy core is distro-agnostic. In fact someone is making something for Ubuntu based on Fedy.

**Comment by Rohan62442** [comment]
Conky is already a part of the official fedora repository so it adds no value to Fedy. And Covergloobus has not been in development since 2010.

Handbrake has been added now and Fedy has numix, arc, ozon and evopop themes.
