### ISSUE TITLE
Unable to prompt during install

### ISSUE THREAD

**Issue by aaronmehar** [folkswithhats/fedy#190]
@satya164 I am trying to add some plugins, one of which requires a prompt and the other some variables, to get username and Firefox profile

I am using the below to get the info I need

```
user=$(who am i |awk '{print $1}')
ffprofile=$(grep "^Path=.*" /home/"$user"/.mozilla/firefox/profiles.ini | cut -c 6-)
echo "Please choose a nickname"
read nicknameirc
```

but when 'Installing' with fedy, the variables are not being expanded nor am I being prompted with the echo.. calling the script directly **ie bash install.sh** works fine, so the script itself works fine.

```
Installed:
  xchat.x86_64 1:2.8.8-26.fc21                                                                                        

Complete!
/bin/mkdir: cannot create directory ‘/home//.config/xchat2/’: No such file or directory
/home//.config/xchat2/servlist_.conf: No such file or directory
/usr/bin/sed: can't read /home//.config/xchat2/servlist_.conf: No such file or directory
```

I just cant figure out the cause.. any ideas?

Thanks!

**Comment by aaronmehar** [comment]
@satya164 just seen your response in Issue #167 regarding confirmation dialogs, have got something in development for that already or just a plan?

**Comment by satya164** [comment]
@aaronmehar It's a plan as of now, and I would also love to implement it, but need to figure out how.

About variables not being expanded, I cannot think of a reason. Can you share your script?

**Comment by aaronmehar** [comment]
@satya164 thanks.

I'll have a chat with some people to get some ideas about the confirmation prompts

**install.sh**
```
#!/bin/bash

user=$(who am i |awk '{print $1}')
echo "Please choose a nickname"
read nicknameirc

dnf -y install xchat

/bin/mkdir /home/"$user"/.config/xchat2/
/usr/bin/wget --quiet http://127.0.01/newdesktop/servlist_.conf -O /home/"$user"/.config/xchat2/servlist_.conf

/usr/bin/sed -i "s/nicknameirc/${nicknameirc}/g" /home/"$user"/.config/xchat2/servlist_.conf
```

and the **metadata.json** (just in case)
```
{
	"icon": "xchat",
	"label": "X Chat",
	"description": "X-Chat is an easy to use graphical IRC chat client for the X Window System.",
	"category": "Apps",
	"scripts": {
		"exec": {
			"label": "Install",
			"command": "run-as-root -s install.sh"
		},
		"undo": {
			"label": "Remove",
			"command": "run-as-root dnf -y --setopt clean_requirements_on_remove=1 erase xchat"
		},
		"status": { "command": "rpm --quiet --query xchat" }
	}
}
```

**Comment by satya164** [comment]
@aaronmehar I'll try with the script later tonight.

About the confirmation dialogs and inputs etc, I would like to have a DBus based API so that the script can communicate with Fedy's UI. The problem is, I cannot find an example with GJS yet.

**Comment by bddenhartog** [comment]
@satya164 Any idea what the status on this is?

**Comment by bddenhartog** [comment]
This issue is being closed as its status is seen as `stale`, or has otherwise been unattended for some time (either by the original reporter, or subsequent users). If this is still an issue or feature that needs to be added, please request that this issue be re-opened instead of creating a new issue.

Thanks!
