### ISSUE TITLE
Add evopop icons and theme.

### ISSUE THREAD

**Issue by PhnxRbrn** [folkswithhats/fedy#196]
Is it possible to have the evopop theme and icons added from the solus-project?

**Comment by satya164** [comment]
Sure. You can send a pull request :)

**Comment by PhnxRbrn** [comment]
Do you have any tips/links/resources on how to create a copr repository from a github project?

**Comment by satya164** [comment]
@PhnxRbrn You'll need to make src.rpm files and give the link in the copr.

**Comment by PhnxRbrn** [comment]
See #228

**Comment by satya164** [comment]
I'll check this weekend @PhnxRbrn
