### ISSUE TITLE
After installing "Gnome development tools" the button does not change to red and label "remove"

### ISSUE THREAD

**Issue by Jobava** [folkswithhats/fedy#206]
After installing "Gnome development tools" the button next to it does not change to red and does not change the label to "remove". The gnome notifications say the installation was successful and console output says (after attempting to install them again)

    Warning: Group 'development-tools' does not exist.
    Package bzr-2.6.0-6.fc21.x86_64 is already installed, skipping.
    Package bzrtools-2.6.0-3.fc21.x86_64 is already installed, skipping.
    Package createrepo-0.10.3-3.fc21.noarch is already installed, skipping.
    Package fedora-packager-0.5.10.5-1.fc21.noarch is already installed, skipping.
    Package rpm-sign-4.12.0.1-6.fc21.x86_64 is already installed, skipping.
    Package rpmdevtools-8.5-1.fc21.noarch is already installed, skipping.
    Package vala-0.26.1-2.fc21.x86_64 is already installed, skipping.
    Package vala-devel-0.26.1-2.fc21.x86_64 is already installed, skipping.
    Package vala-tools-0.26.1-2.fc21.x86_64 is already installed, skipping.
    Package vala-doc-0.26.1-2.fc21.noarch is already installed, skipping.
    Dependencies resolved.
        
    Marking installed:
     Development Libraries
    Complete!

This also means it's not possible to uninstall those packages using the fedy interface.

**Comment by PhnxRbrn** [comment]
What Distro/Version are you running fedy?

**Comment by Jobava** [comment]
Fedora 21

**Comment by PhnxRbrn** [comment]
I am not able to reproduce on a fresh install of Fedora 21. What version of Fedy do you have installed?

**Comment by Jobava** [comment]
I am using the latest one as of the time the issue was posted (and currently latest one) on an updated machine.

Any hints on how to debug it further would be appreciated.

I am also getting this message in the console, by the way:
    Warning: Group 'development-tools' does not exist.

I tried to remove the relevant packages and reinstall them all from fedy again
    yum remove bzr bzrtools createrepo fedore-packager rpm-sign rpmdevtools vala vala-devel vala-tools vala-doc

that also does not work.

In removing those packages, yum also removed: *akmod-VirtualBox* and *akmods* which apparently depend on one of those.

**Comment by gitgt** [comment]
Not reproduced, work fine with Fedy 4.0.6 on F22-x64. Please close.
