### ISSUE TITLE
RPMFusion Not Required

### ISSUE THREAD

**Issue by MagnesiumPC** [folkswithhats/fedy#207]
Error: nothing provides rpmfusion-free-release needed by fedy-4.0.0-1.fc22.noarch

ERROR: FEDORA 22 + GNOME

**Comment by jporradre** [comment]
I'm having the same issue too :(

**Comment by jkudish** [comment]
Likewise. Running Fedora 22 via [Chapeau](http://chapeaulinux.org/)

**Comment by satya164** [comment]
Did you install via the install script? It takes care of installing RPMFusion.

**Comment by jkudish** [comment]
Yes. Here's the full output:

```
$ sudo sh ./fedy-installer
Adding repositories...
Last metadata expiration check performed 2:43:16 ago on Mon Jul 13 09:43:52 2015.
Dependencies resolved.
==============================================================================================================================================================
 Package                                         Arch                            Version                          Repository                             Size
==============================================================================================================================================================
Installing:
 rpmfusion-free-release                          noarch                          22-1                             @commandline                           19 k

Transaction Summary
==============================================================================================================================================================
Install  1 Package

Total size: 19 k
Installed size: 9.7 k
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Error: Transaction check error:
  file /etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora from install of rpmfusion-free-release-22-1.noarch conflicts with file from package chapeau-repos-22-3.noarch
  file /etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-22 from install of rpmfusion-free-release-22-1.noarch conflicts with file from package chapeau-repos-22-3.noarch
  file /etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-23 from install of rpmfusion-free-release-22-1.noarch conflicts with file from package chapeau-repos-22-3.noarch
  file /etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-latest from install of rpmfusion-free-release-22-1.noarch conflicts with file from package chapeau-repos-22-3.noarch
  file /etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-rawhide from install of rpmfusion-free-release-22-1.noarch conflicts with file from package chapeau-repos-22-3.noarch

Error Summary
-------------

Last metadata expiration check performed 2:43:17 ago on Mon Jul 13 09:43:52 2015.
Error: nothing provides rpmfusion-free-release >= 22 needed by rpmfusion-nonfree-release-22-1.noarch
Installing fedy...
Last metadata expiration check performed 2:43:18 ago on Mon Jul 13 09:43:52 2015.
Error: nothing provides rpmfusion-free-release needed by fedy-4.0.0-1.fc22.noarch
```

**Comment by satya164** [comment]
@jkudish What's this repo? `chapeau-repos` ? It's conflicting with RPM Fusion repos.

**Comment by jkudish** [comment]
I'm running [Chapeau](http://chapeaulinux.org/) which is a Fedora 22 remix. I guess they include their own repos.

**Comment by satya164** [comment]
@jkudish But why do they include the RPMFusion keys is beyond me.

**Comment by jkudish** [comment]
I don't know -- any ideas on a possible fix/workaround?

**Comment by PhnxRbrn** [comment]
Since Chapeau comes with its own version of rpmfusion the two lines in the fedy-installer script for adding rpmfusion could be ignored... So an if statement could be placed in the script to check if not Chapeau then try to add the rpmfusion repos to fully solve this problem.

**Comment by jkudish** [comment]
Without those 2 lines, I get the following:

```
Last metadata expiration check performed 1:38:03 ago on Wed Jul 15 17:06:06 2015.
Error: nothing provides rpmfusion-free-release needed by fedy-4.0.0-1.fc22.noarch
```

**Comment by PhnxRbrn** [comment]
@satya164 The spec file for fedy would need to be updated to ignore the requires rpmfusion-free-release and requires rpmfusion-free-release when being installed on Chapeau.  I could take a shot at this if you do not mind.

**Comment by jkudish** [comment]
So looks like this is actually [intentional](http://chapeaulinux.org/forums/topic/korora-repo-working-but-conflicts/)

**Comment by PhnxRbrn** [comment]
Adjusted fedy.spec file to not require RPMFusion when distro name is Chapeau as https://github.com/ozonos/ozon-packaging/pull/4

**Comment by satya164** [comment]
@PhnxRbrn We need a more generic solution. Say, detect if any installed package provides rpmfusion repos and then don't try to install rpmfusion.

Fedy's spec shouldn't be modified here. If Chapeau provides RPM fusion repos, it needs to say that it provides rpm fusion in the repo file. If you know any devs of Chapeau, please mention them here, so we can resolve this the correct way @jkudish

**Comment by PhnxRbrn** [comment]
@satya164 Their spec file lives at github.com/chapeaulinux/chapeau-repos

**Comment by PhnxRbrn** [comment]
@satya164 Just to make sure I fully understand, a provides rpmfusion-free-release and provides rpmfusion-free-release needs added to their repo's spec file, so that if any applications dependency needs rpmfusion this will resolve that issue since they integrate them with their repos

**Comment by satya164** [comment]
@PhnxRbrn Yes.

**Comment by PhnxRbrn** [comment]
Submitted PR over at https://github.com/chapeaulinux/chapeau-repos/pull/1
