### ISSUE TITLE
Master PDF Editor (Install) failed

### ISSUE THREAD

**Issue by dyskette** [folkswithhats/fedy#208]
This is the notification from fedy when trying to install Master PDF Editor on Fedora 22 x86_64. Always reproducible.

![captura de pantalla de 2015-06-07 19-53-57](https://cloud.githubusercontent.com/assets/6687927/8026875/cbb6dc80-0d4f-11e5-9264-c4d4357aa675.png)

**Comment by PhnxRbrn** [comment]
See #229

**Comment by dyskette** [comment]
Closed, because its already merged.

**Comment by gitgt** [comment]
With fedy-3.2.1, which should be the latest version as of today, I can't install Master PDF Editor.

**Comment by gitgt** [comment]
OK, with current Fedy from Git it installs and works - but button remains "install" and not "remove" for me.
I don't know whether that's related to older Master PDF Editor I had before, although I removed it.
