### ISSUE TITLE
Suggestion: clear label with software license

### ISSUE THREAD

**Issue by Gwend4l** [folkswithhats/fedy#211]
Hi!

A quick suggestion: it would be really great to have a clear way to know, for each fedy item, (1) whether or not it's libre software or proprietary software, and (2) the software license.

For instance:

- **Adobe Flash**
    - Browse plug-in and rich internet application runtime.
    - *Proprietary*
- **Atom**
    - A hackable text editor for the 21st Century
    - *Libre (MIT License)*

Or

- **Better font rendering**
    - Improve the font rendering for better readability
    - *Requires patented/proprietary stuff*

Note that for the last example I simply don't know, but I do know that some font rendering can be based an  patented/proprietary stuff (e.G. subpixel rendering is patented), and if it's the case that would be awesome to make it appear. 

My 2 cents! Thanks for Fedy, great work :)

**Comment by Jobava** [comment]
I like this idea too. Would you like to try a pull request?

**Comment by Gwend4l** [comment]
I would, but I am going to be too busy for another week or two. I'll give it a try then, if you're fine with that.

**Comment by satya164** [comment]
We will do more improvements to the license display in future. For now just showing the license should do.
