### ISSUE TITLE
Add zeal

### ISSUE THREAD

**Issue by jalberto** [folkswithhats/fedy#236]
Zeal will be a great addition to Fedy

http://zealdocs.org/
https://github.com/zealdocs/zeal-packaging/tree/master/redhat

Thanks!

**Comment by Rohan62442** [comment]
Zeal has been added to the new [developer plugin repo] (https://github.com/folkswithhats/fedy-plugins-developers/commit/15da06e8e22a02873557782bb54dc74f38f7b1c9) for Fedy.

**Comment by jalberto** [comment]
Thanks!
