### ISSUE TITLE
No fedy package on RPM Fusion repositories

### ISSUE THREAD

**Issue by bryanpvz** [folkswithhats/fedy#242]
I can´t install Fedy...
Because there´s no package "fedy" on any repositories...
Please check it...

**Comment by PhnxRbrn** [comment]
This package lives in the ozon os repos, but they are currently down

**Comment by lfalmeida** [comment]
same here

**Comment by gitgt** [comment]
I don't know why this is closed. Today I got:
"Curl error (28): Timeout was reached for http://goodies.ozon-os.com/repo/22/noarch/ozon-repos-22-5.fc22.noarch.rpm [Connection timed out after 120000 milliseconds]"

**Comment by gitgt** [comment]
OK, wrong issue, that is in issue #240 ozon-os.com repos server is down. 
But than, this one is relevant, because Fedy can't be updated, except from Git.
