### ISSUE TITLE
Virtualbox

### ISSUE THREAD

**Issue by BaflyIr** [folkswithhats/fedy#249]
Hey there

May you add VBox to Fedy?!

Repo: http://download.virtualbox.org/virtualbox/rpm/fedora/virtualbox.repo

**Comment by satya164** [comment]
VirtualBox is available in the RPMFusion repo, which is already added by Fedy.

**Comment by diff-** [comment]
The Vbox in RPMFusion is sh!t. It's not the latest version and usually comes with somes problem to the kernel!
It's recommended to use virtualbox repo instead installing VBox via rpmfusion.

**Comment by BaflyIr** [comment]
But, the vbox in rpmfusion is not the last version. It usually makes some problems!
