### ISSUE TITLE
[F22 x64] Dropbox for Nautilus install failed

### ISSUE THREAD

**Issue by hAh0L13** [folkswithhats/fedy#252]
Hi all.

Title is self-explanatory. Fedy cannot install dropbox, but it successfully install with dnf (nautilus-dropbox.x86_64 1:2.10.0-2.fc22). What I do wrong?

**Comment by Fnux** [comment]
Hum... Fedy download from [dropbox](https://www.dropbox.com/install?os=lnx) and does not use the repo in order to install dropbox. [You can see it right here](https://github.com/folkswithhats/fedy/blob/master/plugins/dropbox.plugin/install.sh).

**Comment by Abhinav1217** [comment]
@hAh0L13 What is the error message? I reinstalled dropbox on my system and it worked smoothly.
Run `sudo fedy` on terminal, and it should provide some errors. Maybe that would help.

**Comment by Abhinav1217** [comment]
It has been months, I don't think this issue persist anymore. Last night I checked it on a VM again to be sure. I am now closing this.

Reopen this if you have more problem.
