### ISSUE TITLE
Please add Chromium

### ISSUE THREAD

**Issue by gitgt** [folkswithhats/fedy#260]
fedy-3.2.1 has Google Chrome, which works. But, please also add Chromium. 

Previously, I was able to do it with: 
sudo curl http://repos.fedorapeople.org/repos/spot/chromium/fedora-chromium-stable.repo -o /etc/yum.repos.d/fedora-chromium-stable.repo  && sudo yum update -y && sudo yum install -y chromium

Now, that script doesn't work for me, because 'fedora-$releasever' doesn't return version, so I just get 'fedora-'. That should be 'fedora-$(rpm -E %fedora)'.

**Comment by gitgt** [comment]
It's https now, and gpg must be checked:
sudo curl https://repos.fedorapeople.org/repos/spot/chromium/fedora-chromium-stable.repo -o /etc/yum.repos.d/fedora-chromium-stable.repo  &&  sudo curl https://repos.fedorapeople.org/repos/spot/chromium/spot.gpg -o /etc/pki/rpm-gpg/spot.gpg  &&  sudo dnf update -y  && sudo dnf install -y chromium

**Comment by satya164** [comment]
This repo doesn't seem to have 32-bit support.

Byt anyways, why would you want to use Chromium instead of Google Chrome? Google Chrome has everything Chromium has, and more.

**Comment by gitgt** [comment]
"This repo doesn't seem to have 32-bit support." - I think a note  "64-bit only" would be enough.
"why would you want to use Chromium instead of Google Chrome?" - I use it because it's OSS, and for Fedy, a matter of choice.

**Comment by satya164** [comment]
@gitgt Well, it might be for you, but not everyone uses 64-bit only, and Fedy tries to support both. Chromium should be no exception.

Anyways, even if it's OSS, it's inferior to Chrome, and doesn't have any additional features. The goal of Fedy has always been convenience, and to be newbie friendly. Following ideals was never the intention.

Adding Chromium might create confusion. Lots of newbies doing know what Chromium is. And they might install it thinking that it's Chrome, and then wonder why Flash is not working.

However, Fedy supports custom plugins. So if you want Chromium, by all means, write a plugin that you can use whether you want, and share with the community.

**Comment by DStewart1997** [comment]
@satya164 How about making a new repo for other plugins that you don't want included by default - like the developer plugins repo? 

@gitgt I'll try creating a plugin for chromium tonight if I have time - and if Satyajit doesn't like the idea of another repo I'll store it on my page.

**Comment by satya164** [comment]
@DStewart1997 That's the idea, we should have a community repo. We also need a way to be able to install plugins from there easily.

**Comment by DStewart1997** [comment]
@satya164 Yeah, would be a nice feature - Maybe a checklist/toggle list or maybe a separate tab with them like the themes and tweaks - a "community" tab?

I think the list sounds better, you could also use it to enable the developer plugins but sounds like more work to implement.

**Comment by DStewart1997** [comment]
@gitgt I've added a chromium plugin [here](https://github.com/DStewart1997/fedy-plugins-community). Satyajit hasn't yet made the new repo so I will store it here for the time being.

I am using [this copr](https://copr.fedoraproject.org/coprs/spot/chromium/) but it hasn't been updated in 2 months so I'm not sure if it's dead but it seems the best way for installing it for now. The [wiki page](https://fedoraproject.org/wiki/Chromium) hasn't been updated since February (before the copr was in use) so the information there seems irrelevant.

To add the plugin just download the zip or clone the git repository and copy the "chromium.plugin" directory to /usr/share/fedy/plugins/. Any issues just let me know.

**Comment by gitgt** [comment]
Thank you. After coping, I also had to set Folder Access: Access Files.

**Comment by bddenhartog** [comment]
Chromium is included in the Fedora repositories by default.

**Comment by bddenhartog** [comment]
Support for community plugins has a more focused issue here: #422
