### ISSUE TITLE
Add version to Fedy

### ISSUE THREAD

**Issue by gitgt** [folkswithhats/fedy#261]
Please add version number to Fedy, for example to the title bar. 
I don't know how to check a version when i't downloaded from git.

**Comment by zagortenay333** [comment]
I wouldn't mind if you added some indication of what version of fedora is supported. I'm waiting on this tool to be available before I install f23.

**Comment by Abhinav1217** [comment]
@gitgt It is better to install fedy using the script. You can then update to stable release with `dnf` Installing it directly from git may be unstable.

@zagortenay333  Fedy would be available for F23 as soon as RPMFusion repos are available for F23. Hence It should be available by the time OS hits stable.
