### ISSUE TITLE
Fedy installer is currently failing, something wrong with repos.

### ISSUE THREAD

**Issue by Jared-Sprague** [folkswithhats/fedy#262]
The command on the fedy homepage has always worked flawlessly for me, but today when I tried installing it I get the below error message:

[jsprague@localhost ~]$ bash -c 'su -c "curl https://satya164.github.io/fedy/fedy-installer -o fedy-installer && chmod +x fedy-installer && ./fedy-installer"'
Password: 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   911  100   911    0     0   6167      0 --:--:-- --:--:-- --:--:--  6197
Adding repositories...
Last metadata expiration check performed 0:21:21 ago on Tue Sep 22 16:50:27 2015.
Curl error (28): Timeout was reached for http://goodies.ozon-os.com/repo/22/noarch/ozon-repos-22-5.fc22.noarch.rpm [Connection timed out after 120002 milliseconds]
Installing fedy...
Last metadata expiration check performed 0:23:22 ago on Tue Sep 22 16:50:27 2015.
No package fedy available.
Error: Unable to find a match.
[jsprague@localhost ~]$

**Comment by Jared-Sprague** [comment]
Looks like goodies.ozon-os.com isn't responding, perhaps you can contact the owner of this server or find an alternative?

**Comment by mrgusvieira** [comment]
i have the same trouble...

**Comment by fangyuthegreen** [comment]
Me too...

**Comment by DStewart1997** [comment]
Temporary workaround.
1. Go to the [release section](https://github.com/folkswithhats/fedy/releases) and click on the [latest release](https://github.com/folkswithhats/fedy/releases/tag/v4.0.5) - V4.0.5.
2. Download the source code. 
3. Unzip it.
4. Open a terminal and go to the new "fedy" directory. 
5. Use ```sudo make install``` to install fedy.

**Comment by madtel** [comment]
same issue here...

**Comment by wilfm** [comment]
https://github.com/folkswithhats/fedy/issues/240 again?

**Comment by Jared-Sprague** [comment]
If ozon-os.com is so unreliable, is there any alternative to fill it's role that is more reliable?

**Comment by wilfm** [comment]
@Jared-Sprague probably -if Github's hosting cannot be used, existing build systems such as [copr](https://copr.fedoraproject.org/) or the [openSUSE](https://build.opensuse.org/) build services are available. Copr may not be usable due to the [forbidden items](https://fedoraproject.org/wiki/Forbidden_items) policy, i'm not sure about openSUSE's [[1]](https://en.opensuse.org/openSUSE:Packaging_guidelines#General_guidelines) [[2]](https://en.opensuse.org/Portal:Packaging). Another possibility could be to ask existing repos such as RPMfusion very nicely...

**Comment by satya164** [comment]
@Jared-Sprague I'm working on moving the repo to a VPS with our own domain. http://folkswithhats.org

**Comment by Jared-Sprague** [comment]
@satya164 Awesome! Thank you! :)

**Comment by Jared-Sprague** [comment]
The installer doesn't hang while trying to connect to goodies.ozon-os.com anymore which is great!  However it's now getting this error at the end "Error: nothing provides ozon-repos needed by fedy-plugins-4.0.5-1.fc22.noarch"

[jsprague@localhost ~]$
[jsprague@localhost ~]$ bash -c 'su -c "curl http://folkswithhats.org/fedy-installer -o fedy-installer && chmod +x fedy-installer && ./fedy-installer"'
Password:
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   923  100   923    0     0   1913      0 --:--:-- --:--:-- --:--:--  1914
Adding repositories...
Last metadata expiration check performed 0:09:58 ago on Thu Sep 24 23:17:42 2015.
Dependencies resolved.
===================================================================================================================================================================================================================
 Package                                                    Arch                                        Version                                            Repository                                         Size
===================================================================================================================================================================================================================
Installing:
 folkswithhats-release                                      noarch                                      1.0.0-1.fc22                                       @commandline                                      6.5 k

Transaction Summary
===================================================================================================================================================================================================================
Install  1 Package

Total size: 6.5 k
Installed size: 154 
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Installing  : folkswithhats-release-1.0.0-1.fc22.noarch                                                                                                                                                      1/1
  Verifying   : folkswithhats-release-1.0.0-1.fc22.noarch                                                                                                                                                      1/1

Installed:
  folkswithhats-release.noarch 1.0.0-1.fc22                                                                                                                                                                       

Complete!
Installing fedy...
Repository for Fedy                                                                                                                                                                 15 kB/s | 5.2 kB     00:00   
Last metadata expiration check performed 0:00:00 ago on Thu Sep 24 23:27:43 2015.
Error: nothing provides ozon-repos needed by fedy-plugins-4.0.5-1.fc22.noarch
(try to add '--allowerasing' to command line to replace conflicting packages)

[jsprague@localhost ~]$
[jsprague@localhost ~]$

**Comment by DStewart1997** [comment]
I don't think @satya164 has updated the website with the new script yet. Not sure if intentional or not but the new script can be found [here](https://github.com/folkswithhats/folkswithhats.org/blob/master/fedy-installer), and seems to work fine. 

It is changed now to be installed from a different repo (http://folkswithhats.org/repo/)...so the script may not have been updated due to issues with the new repo or something - it seemed to take a while to install when I tried it last night.

**Comment by SmashleyG** [comment]
@DStewart1997  - I gave it a try and I am getting what Jared-Sprague is getting still.

**Comment by DStewart1997** [comment]
Try ```dnf config-manager --set-disabled ozon-repos```.

**Comment by brwolfgang** [comment]
Yeah I getting this error with the new repo, too:

    Error: nothing provides ozon-repos needed by fedy-plugins-4.0.5-1.fc22.noarch
    (try to add '--allowerasing' to command line to replace conflicting packages)

I guess the package itself is still referencing the old repo? The script seems fine

**Comment by satya164** [comment]
Can you try again? I fixed the package.

**Comment by satya164** [comment]
About the website, for some reason GitHub is still showing the website even though I've already moved the repo. I'm clueless.

**Comment by brwolfgang** [comment]
No success, the script downloads and install folkswithhats-release-1.0.0-1.fc22.noarch from http://folkswithhats.org/repo/22/RPMS/noarch/ just fine. Then when it downloads and install fedy (the package fedy-plugins-4.0.5-1.fc22.noarch still references ozon.

On that server the modification dates are from yesterday, so I assume they are not the fixed version you're talking about.

**Comment by brwolfgang** [comment]
Nevermind, after a dnf --refresh update the fedy-installer ran just fine.

**Comment by satya164** [comment]
Must be cache issue with dnf. Try clearing dnf's metadata. The latest version should be `fedy-4.0.6-1.fc22.noarch.rpm`

**Comment by SmashleyG** [comment]
@satya164  http://folkswithhats.org <-- This works fine now. 

Thanks heaps.

**Comment by Jared-Sprague** [comment]
Thanks fedy install is working now!

**Comment by joedborg** [comment]
4.0.5 isn't working on Fedora 23
```
Repository successfully enabled.
Failed to synchronize cache for repo 'satya164-numix' from 'https://copr-be.cloud.fedoraproject.org/results/satya164/numix/fedora-23-x86_64/': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried, disabling.
Last metadata expiration check performed 1:12:08 ago on Sun Sep 27 10:12:13 2015.
No package numix-icon-theme available.
No package numix-icon-theme-circle available.
No package numix-gtk-theme available.
Error: Unable to find a match.
```

**Comment by Abhinav1217** [comment]
@joedborg Repos for F23 have not been made yet. Because dependencies and rpmfusion have not been made available to F23 yet. It would be available by the time F23 is released.

**Comment by Abhinav1217** [comment]
Closing it as Main issue has been resolved and issues related to F23 will be solved when OS becomes a stable release.
