### ISSUE TITLE
Fedy Installer Link Broken / Missing

### ISSUE THREAD

**Issue by wayne-hartmann** [folkswithhats/fedy#264]
The link to the installer is broken / it was taken down.

**Comment by AdrianEriksen** [comment]
Same issue here, I get a 404 error when trying the link.

**Comment by AdrianEriksen** [comment]
New link for installer, used http://folkswithhats.org/fedy-installer and it worked!

**Comment by krissch19** [comment]
Could you update the link in your readme.md? Took me quite a while of looking for solutions until I found this Issue here. Cheers

**Comment by Abhinav1217** [comment]
Updated . Readme.
