### ISSUE TITLE
WPS error

### ISSUE THREAD

**Issue by gitgt** [folkswithhats/fedy#269]
WPS was fixed in #173 but it gives Error now. Tried with Fedy 4.0.6 on F22-x64.

**Comment by Abhinav1217** [comment]
I just installed it on my system, It works fine. 
What error message are you receiving? 

Run `sudo fedy` from terminal, it will provide detail about errors.

**Comment by DStewart1997** [comment]
Also cannot install:

Status code: 404 for http://kdl.cc.ksosoft.com/wps-community/download/a19/wps-office-9.1.0.4975-1.a19p1.x86_64.rpm">wps-office-9.1.0.4975-1.a19p1.x86_64.rpm
Failed to show notification: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files

Looks like the link is being parsed wrongly? 
http://kdl.cc.ksosoft.com/wps-community/download/a19/wps-office-9.1.0.4975-1.a19p1.x86_64.rpm works fine when entered manually.

**Comment by Abhinav1217** [comment]
Looks like grep expression is taking some extra characters with the url.
Here is a temp fix, which will work. I will patch it in the app later this week.

Go to `/usr/share/fedy/plugins/wpsoffice.plugin` and open the install.sh
replace line 
```
URL=$(wget "http://wps-community.org/download.html" -O - | tr ' ' '\n' | grep -o "https\?://.*/wps-office-.*$(uname -m).rpm" | head -n 1)
```

With this line,
```
 URL=$(wget "http://wps-community.org/download.html" -O - | tr ' ' '\n' | grep -o "https\?://.*/wps-office-.*$(uname -m).rpm\"" | head -n 1 | rev | cut -c 2- | rev )
```

**Comment by Abhinav1217** [comment]
@DStewart1997 I am closing this.
I have patched the app, and will push it to the repo in few days.

**Comment by DStewart1997** [comment]
@Abhinav1217 Just confirming that your fix does work. Thanks!
