### ISSUE TITLE
Encrypted DVD playback install fail

### ISSUE THREAD

**Issue by t3kg33k** [folkswithhats/fedy#272]
When attempted to install the Encrypted DVD playback (libdvdcss) I receive a failure.
Is there a log or something I can look at and/or provide?

**Comment by t3kg33k** [comment]
Looked in journalctl and it states:

Oct 01 11:48:02 fed22vm pkexec[34515]: ed: Executing command [USER=root] [TTY=unknown] [CWD=/usr/share/fedy/plugins/libdvdcss.plugin] [COMMAND=/usr/share/fedy/bin/run-as-root dnf -y install libdvdcss]
Oct 01 11:48:02 fed22vm org.folkswithhats.fedy.desktop[33898]: Last metadata expiration check performed 1:00:31 ago on Thu Oct  1 10:47:31 2015.
Oct 01 11:48:03 fed22vm org.folkswithhats.fedy.desktop[33898]: No package libdvdcss available.
Oct 01 11:48:03 fed22vm org.folkswithhats.fedy.desktop[33898]: Error: Unable to find a match.

**Comment by DStewart1997** [comment]
Fixed in #273 (I think).

**Comment by t3kg33k** [comment]
Just tried installing it again and received the same failure.
From journalctl:

Oct 03 06:49:09 fed22vm pkexec[4025]: ed: Executing command [USER=root] [TTY=unknown] [CWD=/usr/share/fedy/plugins/libdvdcss.plugin] [COMMAND=/usr/share/fedy/bin/run-as-root dnf -y install libdvdcss]
Oct 03 06:49:09 fed22vm audit[4025]: <audit-1105> pid=4025 uid=1000 auid=1000 ses=1 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 msg='op=PAM:session_open grantors=pam_keyinit,pam_limits,pam_
Oct 03 06:49:10 fed22vm org.folkswithhats.fedy.desktop[3983]: Last metadata expiration check performed 0:26:54 ago on Sat Oct  3 06:22:15 2015.
Oct 03 06:49:10 fed22vm org.folkswithhats.fedy.desktop[3983]: No package libdvdcss available.
Oct 03 06:49:10 fed22vm org.folkswithhats.fedy.desktop[3983]: Error: Unable to find a match.

**Comment by DStewart1997** [comment]
The application hasn't been updated yet to include my changes.

You can use this script to add my changes to your plugins:

    sudo rm -rf /usr/share/fedy/plugins/libdvdcss.plugin && wget https://github.com/DStewart1997/fedy/archive/master.zip && unzip master.zip && sudo mv ./fedy-master/plugins/libdvdcss.plugin /usr/share/fedy/plugins/ && rm -rf fedy-master && rm master.zip

All it does is download my fork of fedy, move the updated libdvdcss.plugin to the fedy plugins directory and clean up the remaining folders.
