### ISSUE TITLE
fedy-installer quits with error

### ISSUE THREAD

**Issue by calbadude** [folkswithhats/fedy#274]
When executing the fedy-installer getting the following error:

$ sudo ./fedy-installer 
Adding repositories...
Status code: 404 for http://folkswithhats.org/repo/20/RPMS/noarch/folkswithhats-release-1.0.0-1.fc20.noarch.rpm
Installing fedy...
No package fedy available.
Error: Nothing to do.

Apparently, the fedy package does not exist.

**Comment by KardiWeb** [comment]
Hello!

Please see: http://folkswithhats.org/repo/

Fedora 20 not supported.

**Comment by Abhinav1217** [comment]
F20 is not supported. You should update your system too as its support is ended by Fedora Community too.  Wait for 2 weeks more and upgrade directly to F23. Fedy will be available there by then.
