### ISSUE TITLE
Multimedia codecs install error

### ISSUE THREAD

**Issue by KardiWeb** [folkswithhats/fedy#275]
Hello Dear Developer!

Multimedia codecs install error.

Error(s) in search for dependencies. Nothing provides amrnb needed by fedy-multimedia-codecs-1.0.0-1.fc22.noarch

**Comment by Abhinav1217** [comment]
Do you still have ozon repo installed? Current release of fedy doesn't use ozon anymore.

**Comment by KardiWeb** [comment]
Ozon repo no used. :)
New: http://folkswithhats.org/

**Comment by Abhinav1217** [comment]
Is it working now? We pushed an update few days ago.

**Comment by Abhinav1217** [comment]
Are you still having issues? Reopen this if needed.
