### ISSUE TITLE
Include WhatsApp

### ISSUE THREAD

**Issue by desyncr** [folkswithhats/fedy#276]
Correct me If I'm wrong but I couldn't find WhatsApp. Can it be added?
https://github.com/Aluxian/WhatsApp-Desktop

Currently there are binary downloads for apt (.deb) so I guess we could PR for a .rpm binary?

Thanks.

**Comment by Abhinav1217** [comment]
Gulpfile does show provision for rpm, but its build failed when I tried it.  I dont think they plans to host and maintain repository. It also has issues related to Facebook blocking its access unless you clear its cache before each run.  Many people were suggesting one of its clone, built using electron-shell. It is located here https://github.com/bcalik/Whatsapp-Desktop/issues . They have a linux build on their roadmap. 

It would be a good to include it as the community plugin we are planning for the future. But till then, you would have to use chrome browser instead.
