### ISSUE TITLE
Jetbrains IDEs are gone

### ISSUE THREAD

**Issue by mejatysek** [folkswithhats/fedy#279]
Is there reason why are all Jetbrains IDEs no longer availeble in Fedy?

**Comment by DStewart1997** [comment]
They are separated into [a separate developers repo](https://github.com/folkswithhats/fedy-plugins-developers). To use these just download that repo and move all of the *.plugin directories to /usr/share/fedy/plugins/.

**Comment by mejatysek** [comment]
Thanks.
