### ISSUE TITLE
[FC22] "Better font rendering" option doesn't work on XFCE

### ISSUE THREAD

**Issue by ghost** [folkswithhats/fedy#283]
# Receive error message when executing the "Better font rendering" option
## System info

**OS:** Fedora 22
**Dependencies:**
Package `freetype-freeworld` from `RPMFusion` installed.
## Steps to produce error message(s)
1. Install `fedy` via the script as advertised on the official webpage. I did add the command `sudo` before `su` because I don't have a superuser account.
2. Click on the `Setup` button besides the "Better font rendering" option.
3. Input password.
4. After some time period the error message "Task failed! Better font rendering (Setup) failed." popup. _The `Setup` button change to the `Revert` button._
5. Click on the `Revert` button to revert the changes made then I clicked on `Setup`.
6. Input password.
7. Receives the error message "Task failed! Better font rendering (Revert) failed.".
## Misc

All the other options works like a charm. It's only "Better font rendering" that doesn't work. I had a `freetype-freeworld` configuration file (`/etc/fonts/local.conf`) I run fedy. I removed the file and rebooted and tested again, same result. I'm didn't notice any change with the config file, so I'm unsure if it even worked.

**Comment by Abhinav1217** [comment]
Please paste here error message detail. 
Open terminal and use `sudo fedy` to launch the application. Then try to setup better font rendering. 
It will provide exact error message details. 

Basically the task installs fedy-font-config using DNF. So there could be some network issue.

**Comment by Abhinav1217** [comment]
Is it working now? We pushed an update few days ago.

**Comment by DStewart1997** [comment]
@Abhinav1217 Can confirm it works fine on F23.

**Comment by Abhinav1217** [comment]
@DStewart1997 Thanks,  I am closing this then.

**Comment by write-your-own-os** [comment]
I found out that my issue was that it didn't work with XFCE, but works like a charm on Gnome. Running Gnome now, so I can't replicate the get the error logs now.

**Comment by mohammadhzp** [comment]
I just installed XFCE, and it's not working
No such schema 'org.gnome.settings-daemon.plugins.xsettings'
Is fedy gnome specific ?

**Comment by satya164** [comment]
Currently fedy only sets the hinting option on Gnome. Pull request is welcome to set it in XFCE

**Comment by bddenhartog** [comment]
Should this be closed? F22 reached end-of-life 2016-07-19: http://fedoraproject.org/wiki/End_of_life

**Comment by bddenhartog** [comment]
Closing - reported version of Fedora is not officially supported.
