### ISSUE TITLE
Suggestion: Add Syncthing

### ISSUE THREAD

**Issue by baldpitter** [folkswithhats/fedy#285]
Syncthing is a great open-source file synchronization application (https://syncthing.net/).
There is also a GUI application (https://github.com/syncthing/syncthing-gtk).

Packages for both are provided via https://copr.fedoraproject.org/coprs/decathorpe/syncthing/.

I would suggest to add two plugins:
1. "Syncthing" (description:  "Open and decentralized file synchronization that replaces proprietary services.") installing only the syncthing package
2. "Syncthing-GTK" (description: "Graphical user interface for Syncthing.") installing syncthing syncthing-gtk

Thank you for your great work!

**Comment by Abhinav1217** [comment]
Thanks, We will give it a look. Currently working on upcoming release. So you might have to wait for this.

**Comment by skmlcd** [comment]
Syncthing is great open source alternative to popular proprietary BTsync. +1 :+1:

**Comment by user501254** [comment]
@Abhinav1217 @baldpitter 
If the merged PR is working well, this can probably be closed.

**Comment by Abhinav1217** [comment]
I Forgot about this. Thanks for reminder.
