### ISSUE TITLE
fedy-installer script

### ISSUE THREAD

**Issue by mlopezcoria** [folkswithhats/fedy#286]
Hey,
I coudn't make the script work on Fedora 22, so I modified it. I tryed this one and it worked all right.

#!/bin/bash
# Script to install Fedy <http://satya164.github.io/fedy/>.
# Copyright (C) 2014  Satyajit sahoo

if [[ ! $(whoami) = "root" ]]; then
    echo "Please run the script as root."
    exit 1
fi

# Add the repo
echo "Adding repository..."
cat <<EOF | tee /etc/yum.repos.d/fedy.repo > /dev/null 2>&1
[fedy]
name=Fedy
type=rpm-md
baseurl=http://download.opensuse.org/repositories/home:/satya164:/fedy/Fedora_\$releasever/
gpgkey=http://download.opensuse.org/repositories/home:/satya164:/fedy/Fedora_\$releasever/repodata/repomd.xml.key
gpgcheck=1
enabled=1
metadata_expire=1d
skip_if_unavailable=1
EOF

# Test if the repo is available for current Fedora version and install the package
echo "Installing fedy..."
fver="$(rpm -E %fedora)"
curl -s -f -L "http://download.opensuse.org/repositories/home:/satya164:/fedy/Fedora_${fver}/repodata/repomd.xml" -o /dev/null
if [[ $? -eq 0 ]]; then
    dnf -y install --nogpgcheck fedy
else
    dnf -y install --nogpgcheck coreutils curl sed tar unzip wget yad
    dnf -y install --nogpgcheck --releasever="$((fver-1))" fedy
fi

# Please report bugs at <http://github.com/satya164/fedy/issues>
# End of the Script

**Comment by DStewart1997** [comment]
Could you possibly be using the old script?

[Here is the website with the current script](http://folkswithhats.org/).
[Here is the source for the installation script](https://github.com/folkswithhats/folkswithhats.org/blob/master/fedy-installer), which is in a separate [repo](https://github.com/folkswithhats/folkswithhats.org).

**Comment by Abhinav1217** [comment]
Script has been moved to new location.  http://folkswithhats.org/

**Comment by mlopezcoria** [comment]
Ok, i think i had the old one, then. Thank you, guys.
