### ISSUE TITLE
Vivaldi install fails

### ISSUE THREAD

**Issue by valentt** [folkswithhats/fedy#287]
Vivaldi install fails on Korora 22:

--2015-11-03 12:40:44--  https://vivaldi.com/download/
Resolving vivaldi.com (vivaldi.com)... 104.20.94.158, 104.20.93.158, 2400:cb00:2048:1::6814:5e9e, ...
Connecting to vivaldi.com (vivaldi.com)|104.20.94.158|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘STDOUT’

-                                                         [ <=>                                                                                                                     ]  12.19K  --.-KB/s   in 0.001s 

2015-11-03 12:40:45 (15.7 MB/s) - written to stdout [12485]

Last metadata expiration check performed 0:29:54 ago on Tue Nov  3 12:10:50 2015.
No package  available.
Error: Unable to find a match.

**Comment by Abhinav1217** [comment]
I checked and it isn't working. Maybe they have changed their download link.  I will check it and push and update later this week.

**Comment by Abhinav1217** [comment]
I have an update commit here https://github.com/Abhinav1217/fedy/tree/master/plugins/vivaldi.plugin . I have checked it and it is working. You can use it for now until I officially forward an update.  I will be pushing a patch at the end of this week, after F23 is released properly.

Just download the `install.sh` from the above link and replace it in `/usr/share/fedy/plugins/vivaldi.plugin`
Let me know if it is working or not for you.

**Comment by valentt** [comment]
It is working. Thanks.
