### ISSUE TITLE
Telegram install fails

### ISSUE THREAD

**Issue by valentt** [folkswithhats/fedy#288]
Telegram install fails on Korora 22:

]777;notify;Command completed;exit12:39 valentt@localhost ~ $ fedy 
Error: This repository does not have any builds yet so you cannot enable it now.
Last metadata expiration check performed 0:29:25 ago on Tue Nov  3 12:10:50 2015.
No package telegram-desktop available.
Error: Unable to find a match.

**Comment by Abhinav1217** [comment]
Try it again. I just reinstalled it and it worked.
```
[Abhinav@abhinav-fed22 ~] $ fedy
Repository successfully enabled.
negativo17 - Steam - Source                     6.4 kB/s | 3.7 kB     00:00    
Fedora 22 - Updates Source                      159 kB/s | 2.0 MB     00:12    
Fedora 22 - x86_64 - Test Updates               340 kB/s | 3.5 MB     00:10    
Fedora 22 - Test Updates Source                  16 kB/s | 389 kB     00:23    
Copr repo for numix owned by satya164            37 kB/s |  97 kB     00:02    
Copr repo for gtk-themes owned by heikoada      173 kB/s | 1.3 MB     00:07    
Fedora 22 - x86_64 - VirtualBox                 256 kB/s |  36 kB     00:00    
google-talkplugin                                12 kB/s | 2.7 kB     00:00    
PlayOnLinux Official repository                  45 kB/s |  77 kB     00:01    
Last metadata expiration check performed 0:00:00 ago on Tue Nov  3 18:39:17 2015.
Dependencies resolved.
=============================================================================================================================================================================
 Package                                      Arch                               Version                                   Repository                                   Size
=============================================================================================================================================================================
Installing:
 telegram-desktop                             x86_64                             0.8.52-1.fc22                             rommon-telegram                              18 M

Transaction Summary
=============================================================================================================================================================================
Install  1 Package

Total download size: 18 M
Installed size: 40 M
Downloading Packages:
telegram-desktop-0.8.52-1.fc22.x86_64.rpm                                                                                                    306 kB/s |  18 MB     01:01    
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                        306 kB/s |  18 MB     01:01     
warning: /var/cache/dnf/rommon-telegram-f3ffe34e7498b2fc/packages/telegram-desktop-0.8.52-1.fc22.x86_64.rpm: Header V3 RSA/SHA1 Signature, key ID 20249ae8: NOKEY
Importing GPG key 0x20249AE8:
 Userid     : "rommon_telegram (None) <rommon#telegram@copr.fedorahosted.org>"
 Fingerprint: 1284 056D DB14 0F77 974B 9E6E C0FE 28E1 2024 9AE8
 From       : https://copr-be.cloud.fedoraproject.org/results/rommon/telegram/pubkey.gpg
Key imported successfully
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Installing  : telegram-desktop-0.8.52-1.fc22.x86_64                                                                                                                    1/1 
  Verifying   : telegram-desktop-0.8.52-1.fc22.x86_64                                                                                                                    1/1 

Installed:
  telegram-desktop.x86_64 0.8.52-1.fc22                                                                                                                                      

Complete!
--2015-11-03 18:40:38--  https://vivaldi.com/download/
Resolving vivaldi.com (vivaldi.com)... 104.20.93.158, 104.20.94.158, 2400:cb00:2048:1::6814:5e9e, ...
Con
```

Re-Open this if it isn't still working.

**Comment by valentt** [comment]
$ fedy
Error: This repository does not have any builds yet so you cannot enable it now.
Last metadata expiration check performed 1:20:02 ago on Tue Nov  3 13:58:34 2015.
No package telegram-desktop available.
Error: Unable to find a match.


Maybe some repo is missing?

**Comment by valentt** [comment]
sudo dnf search telegram
[sudo] password for valentt: 
Last metadata expiration check performed 1:22:12 ago on Tue Nov  3 13:58:34 2015.
=============================================================================================== N/S Matched: telegram ===============================================================================================
python-telegram-cli.x86_64 : Telegram-cli Python2 binding
python3-telegram-cli.x86_64 : Telegram-cli python3 binding
telegram-cli.x86_64 : Linux Command-line interface for Telegram
telegram-cli-data.noarch : Telegram-cli licenses and config files
telegram-purple.x86_64 : Adds support for Telegram to Pidgin, Adium, Finch and other Libpurple based messengers
sigram.x86_64 : A different Telegram client from Sialan.labs

**Comment by valentt** [comment]
telegram install script needs to check if repo for it is correctly installed... it looks it does not check for repo as a dependency...

**Comment by Abhinav1217** [comment]
It is using copr. DNF should automatically manage all its dependencies. 
Try manually enabling copr `sudo dnf copr -y enable rommon/telegram` It usually is kept updated.

**Comment by valentt** [comment]
sudo dnf copr -y enable rommon/telegram 
Error: This repository does not have any builds yet so you cannot enable it now.

**Comment by valentt** [comment]
Manually dowloading https://copr.fedoraproject.org/coprs/rommon/telegram/repo/fedora-22/rommon-telegram-fedora-22.repo and moving it to yum.repos.d directory solved it... is copr broken?

**Comment by Abhinav1217** [comment]
I haven't use Korora for a long time. Copr is working on my test machines. Even on F23. Give me some time to figure this out. If needed We will switch to different repo.

**Comment by LeleDev** [comment]
+1, not working

**Comment by LeleDev** [comment]
Couldn't telegram be downloaded directly from the main site?

**Comment by Abhinav1217** [comment]
copr is now working. Tested it several times on both fedora and korora.

**Comment by xenithorb** [comment]
It's not working again, same problem - except now for most packages

**Comment by Abhinav1217** [comment]
Repos are working ok. I will push update later this month which should update broken links. But only themes repos are broken, Rest are working fine. I just installed telegram last night. It was working fine. 

Try cleaning cache and run fedy from terminal. Give the output here.

**Comment by xenithorb** [comment]
Turns out it was a DNF specific bug in the COPR plugin that I ended up fixing here: https://github.com/rpm-software-management/dnf-plugins-core/pull/189

**Comment by Abhinav1217** [comment]
Nice to know. But now I am confused Why everything went smoothly when I tested it on korora before this release? Looks like I need to create a fresh korora VM to test things from scratch.

Thanks for info.
