### ISSUE TITLE
Incorrect folkswithhats-release package's name

### ISSUE THREAD

**Issue by alunux** [folkswithhats/fedy#290]
[alunux@wonderneko ~]$ bash -c 'su -c "curl http://folkswithhats.org/fedy-installer -o fedy-installer && chmod +x fedy-installer && ./fedy-installer"'
Password: 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   923  100   923    0     0    282      0  0:00:03  0:00:03 --:--:--   282
Adding repositories...
Last metadata expiration check performed 0:00:15 ago on Tue Nov  3 21:03:43 2015.
Status code: 404 for http://folkswithhats.org/repo/23/RPMS/noarch/folkswithhats-release-1.0.0-1.fc23.noarch.rpm
Installing fedy...
Last metadata expiration check performed 0:00:17 ago on Tue Nov  3 21:03:43 2015.
No package fedy available.
Error: Unable to find a match

============================================================================
Please change "folkswithhats-release-1.0.0-1.fc$(rpm -E %fedora).noarch.rpm" to "folkswithhats-release-1.0.1-1.fc$(rpm -E %fedora).noarch.rpm" in fedy-installer file. Thanks.

**Comment by Abhinav1217** [comment]
Is Fedora 23 released? Or you are using beta?
I Just pushed f23 repo but haven't tested it on stable release.  It worked on my Beta-VM because I already had rpmfusion rawhide installed before running the script. Still need to test it on F23

**Comment by Abhinav1217** [comment]
Scratch that, I forgot to pull updates into the website. Sorry for that.  Try it now. It should work.

**Comment by alunux** [comment]
@Abhinav1217 Thank you for your contribution :)

**Comment by alunux** [comment]
@Abhinav1217 Thank you for your contribution :)

**Comment by Abhinav1217** [comment]
Is it working?

**Comment by DStewart1997** [comment]
@Abhinav1217 I'm assuming you already know since you closed the issue but just in case - yeah, it's working fine on F23 stable (some plugins aren't yet but that's to be expected).

**Comment by Abhinav1217** [comment]
Thanks for headsup. I just started downloading it. I will push an update with some more plugin fixes later this week.

**Comment by Abhinav1217** [comment]
@DStewart1997 Are multimedia codecs properly installed?  #291 issue says multimedia codecs were not installed properly.
