### ISSUE TITLE
Missing apps?

### ISSUE THREAD

**Issue by kmare** [folkswithhats/fedy#291]
I just installed fedora 23 and fedy (was on fedora 22 before). I noticed that there are many packages missing that were there before like: atom, brackets, oracle jdk, etc. Am I missing something? Other than that, everything else went smoothly.

**Comment by markubiak** [comment]
It's not going very smoothly for me.  The installer won't even run, and the Multimedia Codecs are failing hard on the old 22 version of Fedy.

**Comment by kmare** [comment]
Actually, the multimedia codecs are failing for me as well. But that's because of a missing library on rpmfusion (libx264) and I guess it'll be fixed soon upstream. Other than that, everything is quite smooth on fedora 23 (and fedy, with the exception of the packages I mentioned above).

**Comment by Abhinav1217** [comment]
@kmare  @markubiak   Wait for few days, All upstreams should be ready by then. Multimedia Codecs should be available by then. I will check some more if we missed something.

@kmare We have reduced number of packages from core install. They are available for download on https://github.com/folkswithhats/fedy-plugins-developers .  Just copy the plugins you want to `/usr/share/fedy/plugins` and it would be available in fedy. 

We are reworking on a easier way to install plugings for future.

**Comment by Abhinav1217** [comment]
I just done downloading F23 ISO,  In Few hours I will get some idea on what's wrong with multimedia codecs.

**Comment by LeleDev** [comment]
Popcorn time installation files too, on F23

**Comment by DStewart1997** [comment]
@LeleDev Popcorn-time has been shutdown. Some of the old devs have moved to [Project Butter](http://butterproject.org/) a legal alternative to popcorn-time (ie. will only have movies and shows that are not copyrighted) but it is still not ready.

**Comment by LeleDev** [comment]
Ok, then it can be safely removed from fedy I guess

**Comment by kmare** [comment]
@Abhinav1217 thank you, didn't know about the fedy-plugins-developers repo. Perhaps you could add a link or some info on the website / github README to let ppl know about it. Thank you for your work!

**Comment by kmare** [comment]
Just wanted to add that the Multimedia Codecs are installing just fine now.

**Comment by markubiak** [comment]
Multimedia codecs are not installing for me.  It's still missing libx264.

**Comment by kmare** [comment]
Not sure if that's what "fixed" it for me, but I also enabled the rpm-fusion updates repo. It seems fedy enables the rpm-fusion testing repo, leaving "updates" disabled.

**Comment by markubiak** [comment]
I can't find the "updates" repo for fedora 23.  There's the "releases" and "testing" repo for 23, but no "updates".

**Comment by kmare** [comment]
hmm are you sure? I have both the free and non-free on a fresh f23 install + fedy.
/etc/yum.repos.d/rpmfusion-free-updates.repo
/etc/yum.repos.d/rpmfusion-nonfree-updates.repo

**Comment by markubiak** [comment]
`ls -1 /etc/yum.repos.d`
adobe-linux-x86_64.repo
bumblebee-nonfree.repo
bumblebee.repo
_copr_satya164-numix.repo
fedora.repo
fedora-spotify.repo
fedora-steam.repo
fedora-updates.repo
fedora-updates-testing.repo
folkswithhats.repo
google-chrome.repo
home:Horst3180.repo
rpmfusion-free-rawhide.repo
rpmfusion-free.repo
rpmfusion-free-updates.repo
rpmfusion-free-updates-testing.repo
rpmfusion-nonfree-rawhide.repo
rpmfusion-nonfree.repo
rpmfusion-nonfree-updates.repo
rpmfusion-nonfree-updates-testing.repo

**Comment by kmare** [comment]
yeah, you have them. Just open both 
 rpmfusion-free-updates.repo
 rpmfusion-nonfree-updates.repo
and set "enabled" to 1 from 0.
Then do a "dnf upgrade" and hopefully it should be alright.

**Comment by markubiak** [comment]
That worked beautifully, I just had to do a `dnf clean all` before the update command.  That's so weird, why would it not be enabled..

**Comment by kmare** [comment]
yeah, it looked weird to me as well when I saw it. "updates" and "testing" are not always in sync and some packages in updates don't even exist in testing (seen it in the past at least), so I guess both are needed if testing is to be enabled. Anyhow, glad it worked for you.

**Comment by LeleDev** [comment]
Multimedia codec installed successfully after enabling these two repo, as suggested by @kmare

**Comment by Abhinav1217** [comment]
I am not so sure why you had to manually enable those repos, I know RPMFusion does have a sync issue from time to time. But never found a reasonable explanation. 

I did a fresh install on 2 system and posted the result in #294 . As you can see, I didn't face any issue. So you guys need to give me something more to search for root of the problem. Like did you upgrade the system or did a fresh install?

**Comment by LeleDev** [comment]
I did a fresh install, and fedy is among the first things I've installed

**Comment by Abhinav1217** [comment]
I did another install in VM, and fedy worked perfectly. Multimedia codec  and font config also installed smoothly. Although I did not notice any visible difference in font smoothness this time. But fonts were pretty smooth before that to, so I am not sure at present if it had any impact or not. 

I am out of ideas why it is not working for some and working for others. In #294 @cereda mentioned that Fusion repos are still pointing to rawhide, Maybe it is because of that reason.

**Comment by LeleDev** [comment]
Also installing rpm fusion after downloading from http://rpmfusion.org/Configuration/, these two repos are stored with enable=0

**Comment by cereda** [comment]
@LeleDev: It's RPM Fusion. If you calculate the checksums of `rpmfusion-free-release-23.noarch.rpm` and `rpmfusion-free-release-rawhide.noarch.rpm`,  you will find out both are the same. It takes some days until the Fusion blokes update their repositories and separate F23 from Rawhide. :wink:

**Comment by Abhinav1217** [comment]
Minor update today adds Atom and Brackets. It also removes Popcorn time because they have shut down.
