### ISSUE TITLE
Swap NOOP SSD tweak for DEADLINE

### ISSUE THREAD

**Issue by egriffith** [folkswithhats/fedy#295]
Given OpenSUSE's comments in their email to Michael over at Phoronix (article available here: http://www.phoronix.com/scan.php?page=news_item&px=openSUSE-42.1-Leap-Kernel) 

I believe that Fedy should at least consider swapping the NOOP scheduler tweak over to DEADLINE.

**Comment by Abhinav1217** [comment]
We will look into it. Also if you have time, you could give us a pull request.

**Comment by Abhinav1217** [comment]
Issue solved with PR #319
