### ISSUE TITLE
Suggestion: create command line switches to install packages

### ISSUE THREAD

**Issue by SuperMatt** [folkswithhats/fedy#297]
I absolutely love what you have done with fedy, but one of the features that would be a big killer would be to be able to run something like the below to install plugins quickly. 

```fedy --install <pluginname>```

I ask for this because I like the functionality that fedy brings via the gui, and I'd like to isntall it along with all the packages in a simple script.

**Comment by satya164** [comment]
Pull requests are welcome. This shouldn't be too difficult to implement.

**Comment by osafi** [comment]
I was also interested in something like this. I have started working on it and should have a pull request soon. I'm working on the following:
```
-l, --list                  List all plugins available and their status
-i, --install plugin        Install a plugin
-u, --uninstall plugin      Remove a plugin
-s, --status plugin         Check if plugin is installed
```

So far I have `--list` implemented. If anyone has a better idea for the listing format let me know.

```
[osafi@obsidian fedy]$ ./fedy --list

====== Apps ======
Archive formats [Installed]
	Utilized by file-roller to extract or compress different formats.
BitTorrent Sync
	Sync easily moves anything, anywhere - all the benefits of the cloud, none of the limitations.
Google Chrome [Installed]
	A fast, simple and secure web browser, built for the modern web.
Multimedia codecs [Installed]
	Utilized by multimedia applications to encode or decode audio or video streams.
Microsoft TrueType core fonts
	Times New Roman, Arial, Comic Sans and other core Microsoft fonts.
Skype
	Stay in touch with your family and friends for free on Skype.
Steam [Installed]
	The ultimate online game platform.
Sublime Text 3
	Sophisticated text editor for code, markup and prose (beta).
Vivaldi
	An advanced browser made with the power user in mind.
WPS Office
	Simple, powerful office suite with a comfortable interface.

====== Themes ======
Arc Theme [Installed]
	A flat theme with transparent elements.
Arc Theme
	A non-transparent version of the Arc theme.
EvoPop themes
	GTK and icon themes from the Solus Project.
Numix themes [Installed]
	GTK and icon themes from the Numix Project.

====== Tweaks ======
Cleanup junk
	Delete junk files such as .DS_Store, desktop.ini, Thumbs.db etc.
Fancy Bash prompt
	Add colors to bash prompt to make it stand out.
Better font rendering
	Improve the font rendering for better readability.
GRUB2 configuration
	Run the GRUB2 configuration scripts and update the configuration file.
SSD I/O scheduler
	Switch to NOOP scheduler to boost performance for SSDs.
Permissive SELinux
	Set SELinux to permissive mode.
Touchpad tap
	Enable systemwide touchpad tap-to-click.
```

**Comment by satya164** [comment]
@osafi Thanks a lot for working on this. I've a bit of suggestion on the commandline options :)

Since it's not always install/uninstall as plugins can do other things, we need more generic names.

```
-l, --list
-e, --exec [plugins...]
-u, --undo [plugins...]
-s, --status [plugins...]
```

**Comment by user501254** [comment]
@osafi @satya164 I have a suggestion/request, please consider.
There can be an option to specify a user defined location. Once Fedy gets the file name (say vivaldi-beta-1.0.344.37-1.x86_64.rpm or ideaIC-15.0.2.tar.gz) to be download, it check that directory to see if that file already exists and if true skip the download part or if false download the file in that particular location.
Of course for plugins that do not require any package downloads such as those which install from copr, this option is not applicable.

This can save significant time/bandwidth if the user already has the file somewhere and the user can also easily reuse the downloaded file

**Comment by satya164** [comment]
@user501254 Most of the plugins already use the existing cache if available.

e.g. - https://github.com/folkswithhats/fedy/blob/master/plugins/skype.plugin/install.sh#L3

You can copy the cache directory `/var/cache/fedy` to a new computer to reuse it. Note that Fedy doesn't enforce the use of cache. But it's just a convention.

**Comment by user501254** [comment]
I think custom locations would have been more convenient. Copying files into and out of `var/cache/fedy/xyz` comparatively needs more effort on the user's side.

**Comment by satya164** [comment]
@user501254 Why copy files separately? Just copy the whole folder. Custom paths will make everything more complicated IMO.

**Comment by user501254** [comment]
Copying the whole `var/cache/fedy/` would work only one way, ie. people can use files downloaded by fedy@PC1 on fedy@PC2 (or even manual install). 

But if the user already has the file (`xyz.tar.gz`; downloaded through a browser, not fedy) on an external drive for some plugin (`xyz`), one would have to copy that file into the specific plugin folder under `var/cache/fedy` which requires some extra steps like creating the folder, a minor inconvenience.

**Comment by SuperMatt** [comment]
This really doesn't fit in to the spec of the request that I made, so I don't know why it's in here. I agree with satya164, that it doesn't warrant custom locations for these files, and would also suggest that using your own cache would be dangerous. Someone could simply rename an rpm or .tar.gz file to match the latest version and install an old or compromised version.

Fedy needs root access so that it can install trusted files, and that trust will be gone if packages could be installed from local sources. I am going to close this issue request.

**Comment by satya164** [comment]
@user501254 I think that's reasonable. Otherwise you've to manually specify location for all plugins separately and you won't be able to do anything in batch.

It'll also make both the UI and the plugins more complicated.

**Comment by satya164** [comment]
@user501254 If you have an idea on how to implement this without overcomplicating things, then we can look into it.

**Comment by user501254** [comment]
@SuperMatt On the contrary, I believe that this would make things more transparent. Even if someone does a little hacking like renaming the externally downloaded file to match the latest version, I would assume they are fully aware of what they are doing and the risks involved. Fedy can't be blamed if anything goes wrong in that case.

@satya164 
- At it's simplest form,
  Something like

      fedy -e jre -d "/home/username/Downloads"
  should pass the named custom location argument to individual [install script](https://github.com/folkswithhats/fedy/blob/master/plugins/jre.plugin/install.sh), so that [`cd "/var/cache/fedy/jre"`](https://github.com/folkswithhats/fedy/blob/master/plugins/jre.plugin/install.sh#L3) ultimately becomes `cd "/home/username/Downloads"` for that particular instance and use `wget` with `-nc` option.

- extended version for batch operations
  Multiple plugins with single custom location

      fedy -e jre skype -d "/home/username/Downloads"
  Multiple plugins with multiple custom locations

      fedy -e jre -d "/run/media/username/F463-A352" skype -d "/home/username/Downloads"

**Comment by satya164** [comment]
@user501254 wget won't match files which are not the correct ones.

There are several problems here,

1. How is it going to work with the UI, I don't want to have features in command line which are not there in the UI
2. Most importantly, how is the implementation going to work, I'm sure the Ui/CLI can be figured out, but implementation is not that simple, and going to put additional maintenance overhead
3. This is not something which you'll need do very frequently, so is the maintenace overhead associated with this worth it?
4. With the current approach you need to copy files to correct locations once, then you can just copy the whole folder, with the your approach, you need to reproduce the exact same file locations on all computers and also need to copy the command line too (by having to create a text file and pasting it there may be), or enter the custom locations all over again.

**Comment by user501254** [comment]
I was thinking this to be a CLI only feature but since fedy can't have anything in the CLI that's not in the GUI, there's no point in continuing further. I'm sorry about the noise.

**Comment by satya164** [comment]
@user501254 As I said, we can figure out the UI, the main issue is with the implementation

**Comment by user501254** [comment]
@satya164 once @osafi has made their PR, I could give it a try and see if this can be done feasibly in the CLI. However the GUI part will be complicated (specially for batch operations) and is not worth implementing.
