### ISSUE TITLE
Numix fails, tries to pull from non-existant Fedora 23 repo

### ISSUE THREAD

**Issue by NiHab** [folkswithhats/fedy#300]
Tries to get https://copr-be.cloud.fedoraproject.org/results/satya164/numix/fedora-23-x86_64/ which does not exist (yet?)

**Comment by mapringg** [comment]
same problem :warning:

**Comment by Abhinav1217** [comment]
Numix team will rebuild their repo soon.  Till then you would have to wait.

**Comment by Abhinav1217** [comment]
Will push an update soon.
