### ISSUE TITLE
fedy gives blank UI

### ISSUE THREAD

**Issue by user501254** [folkswithhats/fedy#304]
Builds with `make install` on source works fine but when I install fedy using `dnf install fedy`, on launching fedy I cant see any list of apps, themes or tweaks.

![image](https://cloud.githubusercontent.com/assets/6129517/11165874/154ee9fc-8b43-11e5-8519-12bed35a8016.png)

DNF installs:

    ================================================================================
     Package          Arch          Version              Repository            Size
    ================================================================================
    Installing:
     fedy             noarch        4.0.9-1.fc23         folkswithhats        6.9 k
     fedy-core        noarch        4.0.9-1.fc23         folkswithhats         33 k

    Transaction Summary
    ================================================================================
    Install  2 Packages

**Comment by user501254** [comment]
`dnf erase fedy-plugins` solved the issue.

**Comment by Abhinav1217** [comment]
Did you use the script from http://folkswithhats.org/ ?

**Comment by user501254** [comment]
Yes, initially I used the script on the website but a few days ago I reinstalled it from source (`make install`) in order to test some plugin I was working on. I then removed it (`make uninstall`) and tried installing from the repository again, which gave me this.

**Comment by Abhinav1217** [comment]
Maybe uninstall didn't clean packages properly. In Future, You can just put your plugins in `~/.local/share/fedy/plugins` .  They would be listed in Fedy.

**Comment by user501254** [comment]
That's what I figured but shouldn't `make uninstall` automatically remove `fedy-plugins` as well?

**Comment by Abhinav1217** [comment]
I followed your steps on a vm and couldn't replicate it. Maybe it was some cache issue.  I will look further into makefile. 

I am closing this for now.
