### ISSUE TITLE
Helvetica's replacement Nimbus Sans L has bad kerning on websites

### ISSUE THREAD

**Issue by dyskette** [folkswithhats/fedy#305]
As bug https://bugzilla.redhat.com/show_bug.cgi?id=1160935 on RedHat, this still occurs on Fedora 23.

Do you think this could be addresed on fedy?

Fedy has more possibilities to provide a replacement or to modify the current behaviour on local.conf.

**Comment by Abhinav1217** [comment]
I don't think solving that bug is within the scope of fedy. `fedy-font-config` does provide better font rendering by implementing common practices like setting text-hinting, and antialias values.  It can be enabled in `Tweaks` section of fedy.
