### ISSUE TITLE
fedy can't install - (No package fedy available)

### ISSUE THREAD

**Issue by pyaehein** [folkswithhats/fedy#309]
OS - Fedora23 (64bit) Fresh Install

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   923  100   923    0     0    827      0  0:00:01  0:00:01 --:--:--   827
Adding repositories...
Installing fedy...
Last metadata expiration check performed 0:25:55 ago on Sun Nov 22 19:24:44 2015.
No package fedy available.
Error: Unable to find a match.

**Comment by Abhinav1217** [comment]
Try `sudo dnf -y update --refresh` and then use the script again. Maybe there is some issue with old cache.

I was updating server last night, so it was down for about 10 minutes. Maybe it was bad timing.

**Comment by Abhinav1217** [comment]
@pyaehein  Any update on the situation. Is it working now or not. Do I close this?

**Comment by pyaehein** [comment]
I updated refresh what u said. But sadly can't fix :(

Complete!
[nnieheayp@ph-fedora23 ~]$ fedy
bash: fedy: command not found...
[nnieheayp@ph-fedora23 ~]$ bash -c 'su -c "curl http://folkswithhats.org/fedy-installer -o fedy-installer && chmod +x fedy-installer && ./fedy-installer"'
Password: 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   923  100   923    0     0    433      0  0:00:02  0:00:02 --:--:--   433
Adding repositories...
Installing fedy...
Last metadata expiration check performed 0:12:14 ago on Sat Nov 28 11:05:57 2015.
No package fedy available.
Error: Unable to find a match.

**Comment by Abhinav1217** [comment]
Is it working now?

**Comment by pyaehein** [comment]
Yes, working now. I reinstalled fedora. Thank you.
