### ISSUE TITLE
Fedy install one-liner fails when no root password is configured

### ISSUE THREAD

**Issue by mah17** [folkswithhats/fedy#311]
The current install one-liner will fail if there wasn't a root password set in Anaconda during install. If you create a user that's an Administrator during setup, it no longer requires a root password. Since `su -c` expects root's password, setup fails.

I'm not sure what the best alternative would be. Maybe some lines in `fedy-installer` that detects if `sudo` is installed, and uses that instead of `su -c`.

**Comment by Abhinav1217** [comment]
As an alternative, for now you can download the script "http://folkswithhats.org/fedy-installer" and run it locally using sudo `sudo ./fedy-installer` .
