### ISSUE TITLE
Console for debugging

### ISSUE THREAD

**Issue by blackjackshellac** [folkswithhats/fedy#321]
It would be nice to be able to show a console to give more details when an install fails.  I've had a couple of failures (one related to a dependency rpm version).  The notifications are not really sufficient to understand why an install has failed.  This morning I got,

"Task failed! Microsoft TrueType core fonts (Install) failed."

When this happens I usually go into the script code to find out what is going on but for most end users this is not ideal.

**Comment by satya164** [comment]
You can start fedy from the console to see logs.

**Comment by Abhinav1217** [comment]
I am closing this as it is already implemented.  More verbosity can be added if needed.
