### ISSUE TITLE
Add https on repo urls

### ISSUE THREAD

**Issue by comzeradd** [folkswithhats/fedy#322]
Have you consider of adding https on the repo url(s)?
Downloading packages over http is not a very good practice.

**Comment by Abhinav1217** [comment]
Most urls have both http and https in its regex expression. Some community plugins did have hard coded urls but we update them when found.   If you are talking about folkswithhats dnf repo, We shifted it to a VPS from OBS.  I haven't configured ssl certificate on the server yet. But Eventually it will be configured.
