### ISSUE TITLE
Disk I/O Scheduler tweak fails

### ISSUE THREAD

**Issue by valentt** [folkswithhats/fedy#323]
Messages when fails

/usr/share/fedy/plugins/ioscheduler.plugin/setup.sh: line 3: non-rotating-scheduler=deadline: command not found
/usr/share/fedy/plugins/ioscheduler.plugin/setup.sh: line 4: rotating-scheduler=deadline: command not found

**Comment by Abhinav1217** [comment]
Open fedy from terminal  using `sudo fedy` command. Then use the plugin . Post the terminal Output here.

**Comment by Abhinav1217** [comment]
I have notified @rishadafc , author of this plugin, to this issue.

**Comment by Abhinav1217** [comment]
A Pull request has been made on this. I am planning to release an update later this month.
