### ISSUE TITLE
Add MTP support

### ISSUE THREAD

**Issue by otoman** [folkswithhats/fedy#330]
Please consider adding MTP support. Thank you :)

**Comment by Abhinav1217** [comment]
What is MTP? Please provide some link.

**Comment by otoman** [comment]
MTP (Media Transfer Protocol) http://uwot.eu/blog/2014/12/fedora-21-and-mtp/

**Comment by Abhinav1217** [comment]
Do we really need a plugin for it? MTP support in F23 is really great. That article looks like, is for xfce spin of older F21.

  libmtp  was already available now in system. I also checked on testing VM, Gnome, Kde, lxde, xfce, and cinnamon spins of F23. It was there on all of them.

In fact only gvfs-mtp and simple-mtpfs was not pre installed in F23 spins.

**Comment by Abhinav1217** [comment]
Closing this as MTP support in F23 is already there and is going to be improved in future release.
