### ISSUE TITLE
Fedy behind proxy

### ISSUE THREAD

**Issue by meghprkh** [folkswithhats/fedy#332]
Fedy does not work properly behind a proxy.

I edited `run-as-root` script so that it also sets proxy variables from the current environment but I am unable to make it work.

I edited `run-as-root` line 12 to

``` bash
exec pkexec "$0" env HTTP_PROXY=$HTTP_PROXY HTTPS_PROXY=$HTTPS_PROXY FTP_PROXY=$FTP_PROXY "$@"
```

It correctly prints the proxy variables on running `env` in any plugin's script but `wget`/`curl` donot work... keep on getting connection refused

**Comment by Abhinav1217** [comment]
I haven't tested fedy in proxy environment.  I did use a VPN.   I will need to look into it.   how is your  proxy configured?

**Comment by meghprkh** [comment]
```
$ cat /etc/environment
http_proxy="http://proxy.iiit.ac.in:8080/"
https_proxy="http://proxy.iiit.ac.in:8080/"
ftp_proxy="http://proxy.iiit.ac.in:8080/"
no_proxy="localhost,127.0.0.1,.iiit.ac.in"

HTTP_PROXY="http://proxy.iiit.ac.in:8080/"
HTTPS_PROXY="http://proxy.iiit.ac.in:8080/"
FTP_PROXY="http://proxy.iiit.ac.in:8080/"
NO_PROXY="localhost,127.0.0.1,.iiit.ac.in"

```

**Comment by Abhinav1217** [comment]
I couldn't replicate it at that time, and not F25 either. I used OpenVPN for proxy. @bddenhartog  If you can replicate it, we can keep it open, or else we can close it.

**Comment by meghprkh** [comment]
@Abhinav1217 On Fedora 25, it seems to work! I installed Numix theme using Fedy

**Comment by Abhinav1217** [comment]
OK then, I will close it.
