### ISSUE TITLE
Add TLP (linux advanced power management) plugin

### ISSUE THREAD

**Issue by SaeedMasoumi** [folkswithhats/fedy#334]
Hey guys,
I found a pull request here [#320](https://github.com/folkswithhats/fedy/pull/320), but it deleted and didn't merge.
Is there any problem? TLP is very useful for laptop batteries.

**Comment by Abhinav1217** [comment]
You can install TLP using `dnf -y install tlp tlp-rdw`.   Plugin was not included because it didn't met criteria at that time. We may add it in future if demand is there.
