### ISSUE TITLE
Microsoft TrueType core fonts link busted

### ISSUE THREAD

**Issue by t3kg33k** [folkswithhats/fedy#336]
Just attempted to install the fonts and received a failed. Looking at journalctl here is what I found:

Feb 08 20:41:43 edfed23 org.folkswithhats.fedy.desktop[15604]: No package $(wget available.
Feb 08 20:41:43 edfed23 org.folkswithhats.fedy.desktop[15604]: No package http://mscorefonts2.sourceforge.net/ available.
Feb 08 20:41:43 edfed23 org.folkswithhats.fedy.desktop[15604]: No package -O available.
Feb 08 20:41:43 edfed23 org.folkswithhats.fedy.desktop[15604]: No package - available.
Feb 08 20:41:43 edfed23 org.folkswithhats.fedy.desktop[15604]: No package | available.
Feb 08 20:41:43 edfed23 org.folkswithhats.fedy.desktop[15604]: Package grep-2.22-6.fc23.x86_64 is already installed, skipping.
Feb 08 20:41:43 edfed23 org.folkswithhats.fedy.desktop[15604]: No package -Po available.
Feb 08 20:41:43 edfed23 org.folkswithhats.fedy.desktop[15604]: No package https://downloads.sourceforge.net/project/mscorefonts2/rpms/msttcore-fonts-installer-[0-9.]{3}-[0-9].noarch.rpm) available.
Feb 08 20:41:43 edfed23 org.folkswithhats.fedy.desktop[15604]: Error: Unable to find a match.

**Comment by Abhinav1217** [comment]
It is working on a fresh gnome vm.
Run fedy from terminal and perform task. 
Then post output from terminal here.

**Comment by t3kg33k** [comment]
I'm running Fedora 23.
Odd. It worked from terminal but fails when launching Fedy from within Gnome and using the GUI.

**Comment by t3kg33k** [comment]
I just tried the same thing again on Fedora 23 build on my personal laptop and received this error:

RPM Fusion for Fedora 23 - Nonfree - Test Updates                       387 kB/s |  76 kB     00:00    
Repository for Fedy                                                      17 kB/s | 5.1 kB     00:00    
google-chrome                                                            48 kB/s | 3.4 kB     00:00    
RPM Fusion for Fedora 23 - Free - Test Updates                          888 kB/s | 321 kB     00:00    
Fedora 23 - x86_64 - VirtualBox                                         447 kB/s |  57 kB     00:00    
Last metadata expiration check performed 0:00:00 ago on Tue Feb 16 05:52:10 2016.
No package $(wget available.
No package http://mscorefonts2.sourceforge.net/ available.
No package -O available.
No package - available.
No package | available.
Package grep-2.22-6.fc23.x86_64 is already installed, skipping.
No package -Po available.
No package https://downloads.sourceforge.net/project/mscorefonts2/rpms/msttcore-fonts-installer-[0-9.]{3}-[0-9].noarch.rpm) available.
Error: Unable to find a match.

**Comment by Gujs** [comment]
Same problem with fresh Fedora 23 install

`Failed to synchronize cache for repo 'Dropbox' from 'http://linux.dropbox.com/fedora/23/': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried, disabling.
Last metadata expiration check performed 0:10:30 ago on Tue Feb 16 22:16:32 2016.
No package $(wget available.
No package http://mscorefonts2.sourceforge.net/ available.
No package -O available.
No package - available.
No package | available.
Package grep-2.22-6.fc23.x86_64 is already installed, skipping.
No package -Po available.
No package https://downloads.sourceforge.net/project/mscorefonts2/rpms/msttcore-fonts-installer-[0-9.]{3}-[0-9].noarch.rpm) available.
Error: Unable to find a match.
Failed to show notification: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
`

**Comment by isantolin** [comment]
Same problem on Fedora 23

> Last metadata expiration check performed 0:00:00 ago on Wed Feb 17 05:03:43 2016.
Nenhum pacote $(wget disponível.
Nenhum pacote http://mscorefonts2.sourceforge.net/ disponível.
Nenhum pacote -O disponível.
Nenhum pacote - disponível.
Nenhum pacote | disponível.
Package grep-2.22-6.fc23.x86_64 is already installed, skipping.
Nenhum pacote -Po disponível.
Nenhum pacote https://downloads.sourceforge.net/project/mscorefonts2/rpms/msttcore-fonts-installer-[0-9.]{3}-[0-9].noarch.rpm) disponível.
Error: Unable to find a match.
Failed to show notification: GDB

**Comment by Abhinav1217** [comment]
I am pushing an update by end of this week. I was suppose to push it today but it got delay.  This will be fixed in the update.

**Comment by Abhinav1217** [comment]
It has been fixed.  Will push an update by end of this week.
