### ISSUE TITLE
Problem with new Sublime-Text Build (3103)

### ISSUE THREAD

**Issue by 636stefan** [folkswithhats/fedy#337]
Hello, 
Just today a new version of sublime-text 3 was released. After a fresh install I wanted to install sublime and I got the following error: 

<pre><code>
-2016-02-09 17:06:22--  http://www.sublimetext.com/3
Resolving www.sublimetext.com (www.sublimetext.com)... 209.20.75.76
Connecting to www.sublimetext.com (www.sublimetext.com)|209.20.75.76|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 26199 (26K) [text/html]
Saving to: ‘STDOUT’

-                   100%[=====================>]  25.58K  32.2KB/s   in 0.8s   

2016-02-09 17:06:23 (32.2 KB/s) - written to stdout [26199/26199]

--2016-02-09 17:06:23--  http://c758482.r82.cf2.rackcdn.com/sublime_text_3_build_3103_x64.tar.bz2
Resolving c758482.r82.cf2.rackcdn.com (c758482.r82.cf2.rackcdn.com)... 61.213.151.42, 61.213.151.35, 2600:140e:1::17c9:6611, ...
Connecting to c758482.r82.cf2.rackcdn.com (c758482.r82.cf2.rackcdn.com)|61.213.151.42|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-02-09 17:06:25 ERROR 404: Not Found.

bzip2: Compressed file ends unexpectedly;
	perhaps it is corrupted?  *Possible* reason follows.
bzip2: Inappropriate ioctl for device
	Input file = (stdin), output file = (stdout)

It is possible that the compressed file(s) have become corrupted.
You can use the -tvv option to test integrity of such files.

You can use the `bzip2recover' program to attempt to recover
data from undamaged sections of corrupted files.

tar: Child returned status 2
tar: Error is not recoverable: exiting now
Failed to show notification: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
</pre></code>

I use a brand new Fedora 23 x86_64 installation. I tested several vpns and always got the same result.
Any ideas ? 

Btw. thanks for this awesome project.

**Comment by 636stefan** [comment]
**UPDATE:**
It looks like with the new releases there have been a few changes in the download-infrastructure. 
So I just changed the server-address in line 14 of the install script 
`/usr/share/fedy/plugins/sublimetext.plugin/install.sh`

from: 
`URL="http://c758482.r82.cf2.rackcdn.com/$(wget http://www.sublimetext.com/3 -O - | grep -Po sublime_text_3_build_[0-9]{4}_$ARCH.tar.bz2)"
`

to: 
`URL="http://download.sublimetext.com/$(wget http://www.sublimetext.com/3 -O - | grep -Po sublime_text_3_build_[0-9]{4}_$ARCH.tar.bz2)"
`

Works just fine for me. Any thoughts on that?

**Comment by satya164** [comment]
@636stefan Awesome. Up for sending a PR?

**Comment by 636stefan** [comment]
@satya164 Done.
