### ISSUE TITLE
Master PDF editor (install) failed

### ISSUE THREAD

**Issue by t3kg33k** [folkswithhats/fedy#340]
Just tried installing Master PDF editor in Fedora 23 by launching Fedy from command line and received this error:

-2016-02-16 06:00:44--  http://code-industry.net/free-pdf-editor.php
Resolving code-industry.net (code-industry.net)... 188.40.138.131
Connecting to code-industry.net (code-industry.net)|188.40.138.131|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://code-industry.net/free-pdf-editor.php [following]
--2016-02-16 06:00:45--  https://code-industry.net/free-pdf-editor.php
Connecting to code-industry.net (code-industry.net)|188.40.138.131|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://code-industry.net/free-pdf-editor/ [following]
--2016-02-16 06:00:45--  https://code-industry.net/free-pdf-editor/
Reusing existing connection to code-industry.net:443.
HTTP request sent, awaiting response... 200 OK
Length: 23471 (23K) [text/html]
Saving to: ‘STDOUT’

-                         100%[=====================================>]  22.92K  --.-KB/s    in 0.004s  

2016-02-16 06:00:45 (5.76 MB/s) - written to stdout [23471/23471]

**Comment by Abhinav1217** [comment]
This is not the error.  301 is HTTP redirect, which is common when downloading things. Download is redirected a few times, in this case, from port 80 to port 443 which is https port.   Last one is 200 which is HTTP code for OK. After that It is downloaded. see the last line.  

Just to be sure, I will test this plugin on couple of VM before pushing update this week.

**Comment by t3kg33k** [comment]
Either way, it displays a failed message in the GUI and does not install.

**Comment by Abhinav1217** [comment]
Should be fixed in upcoming update.

**Comment by Abhinav1217** [comment]
Ok Found the cause.  They changed the link. It is now fixed. Will push an update soon.
