### ISSUE TITLE
Master PDF, MS Fonts, and SublimeText3 not working

### ISSUE THREAD

**Issue by jonnjonzzn** [folkswithhats/fedy#341]
Fresh install of F23 and then complete update.  Fedy failing for Master PDF, MS Fonts, and SublimeText3.

I should mention I disable the RPM Fusion testing repo's after I install Fedy.

**Comment by DStewart1997** [comment]
These have been fixed - an update should be released soon. See #336, #337 & #340.

If you need these now you can always build from source. Download fedy as a zip, extract, cd into the folder and use `sudo make install`.

**Comment by jonnjonzzn** [comment]
Thank you, Dan. Closing as this turned out to be a duplicate of the three mentioned above.
