### ISSUE TITLE
fedy --help not working correctly.

### ISSUE THREAD

**Issue by RobbHendershot** [folkswithhats/fedy#343]
I am running "fedy --help" as shown in the FAQ but it only opens the GUI and does not return the list of available commands.

**Comment by Abhinav1217** [comment]
Command line usage has been removed in the 4.x rewrite.  Fedy currently is GUI only tool. Fedy Legacy was written in bash.  4.x is written in GJS. This helps us work on improvement of plugins for fedy. 

You can use `fedy` command to launch Fedy in which you would get output of the commands being executed by the plugins. 

Basic command line usage has been requested but is currently low priority.
