### ISSUE TITLE
Atom install fails on Fedora 22

### ISSUE THREAD

**Issue by valentt** [folkswithhats/fedy#345]
$ sudo dnf copr -y enable helber/atom
[sudo] password for xxx: 
Error: This repository does not have any builds yet so you cannot enable it now.

But when I manually added atom repo install works... please check it out.

**Comment by Abhinav1217** [comment]
It worked fine on a fresh vm.  And also on my current machine.

```
Abhinav@abhinav-f23 ~] $ sudo dnf copr -y enable helber/atom
[sudo] password for Abhinav: 
Repository successfully enabled.
```
```
[Abhinav@abhinav-f23 ~] $ fedy
Repository successfully disabled.
Dependencies resolved.
====================================================================================================================================
 Package                    Arch                  Version                                         Repository                   Size
====================================================================================================================================
Removing:
 atom                       x86_64                1.5.4-1.fc23                                    @helber-atom                191 M
 atom-libs                  x86_64                1.5.4-1.fc23                                    @helber-atom                 16 M
 http-parser                x86_64                2.0-9.20121128gitcd01361.fc23                   @fedora                      56 k
 zsh                        x86_64                5.1.1-4.fc23                                    @updates                    6.2 M

Transaction Summary
====================================================================================================================================
Remove  4 Packages

Installed size: 213 M
Running transaction check
Transaction check succeeded.
Running transaction test
```
```
[Abhinav@abhinav-f23 ~] $ fedy
[Abhinav@abhinav-f23 ~] $ sudo bash /usr/share/fedy/plugins/atom.plugin/install.sh 
Repository successfully enabled.
Last metadata expiration check performed 2:29:23 ago on Sun Mar 13 13:30:53 2016.
Package atom-1.5.4-1.fc23.x86_64 is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!
[Abhinav@abhinav-f23 ~] $ 
```

I can not replicate it.  Maybe it was some cache issue. Please try again. For safe measures do `sudo dnf clean all` and then try installing atom from fedy.

**Comment by 1dot75cm** [comment]
https://copr.fedorainfracloud.org/coprs/mosquito/atom/
It's better than `helber/atom`.

**Comment by DStewart1997** [comment]
I've put in [PR24](https://github.com/folkswithhats/fedy-plugins-developers/pull/24) on the developer plugins repo to install directly from atom. 
Not sure if copr is preferred rather than downloading from the Atom site but this would resolve any issues with copr repos being down or out of date.

**Comment by Abhinav1217** [comment]
@1dot75cm We are using mosquito's copr for visual studio. Maybe we can switch over it for atom too. helber keeps its repo updated too. 

@DStewart1997  I think Copr would be better,  Can rpm be updated via `dnf` in future?

**Comment by DStewart1997** [comment]
Ah right, fair one. I knew I was forgetting something.

**Comment by 1dot75cm** [comment]
Thanks @Abhinav1217 . It will be better.

**Comment by Abhinav1217** [comment]
Closing as it has been resolved.  Copr is active and updated.  Switching to mosquito's copr will be discussed.
