### ISSUE TITLE
Add a menu to add CCRMA fedora repo for Music tools

### ISSUE THREAD

**Issue by ycollet** [folkswithhats/fedy#346]
Add a menu to add CCRMA fedora repo for Music tools

http://ccrma.stanford.edu/planetccrma/software/installplanettwenty.html

**Comment by Abhinav1217** [comment]
Whats the advantage of it over current rpmfusion implementation?

**Comment by ycollet** [comment]
In ccrma, the proposed packages are related to music (synth, score editor, etc) and not related to multimedia.
ccrma proposes also a realtime kernel.
