### ISSUE TITLE
The AppData file has 3 broken links.

### ISSUE THREAD

**Issue by vharsh** [folkswithhats/fedy#349]
The [fedy.appdata.xml ] (https://github.com/folkswithhats/fedy/blob/master/fedy.appdata.xml) file has _broken links_ to
- screenshot ( line#16 & 17 )
- homepage url ( line#19 )

**Comment by userimack** [comment]
The main problem is satya164.github.io is showing 404 error.

**Comment by satya164** [comment]
Would be great if somebody can move the images to https://github.com/folkswithhats/folkswithhats.org/ and send a PR to update the appdata.

**Comment by userimack** [comment]
I will do it.

**Comment by userimack** [comment]
@satya164 are you asking to change the link to https://github.com/folkswithhats/folkswithhats.org/fedy/images/apps.jpg ? or something else as there is no images on that link

**Comment by Abhinav1217** [comment]
I thought I had fixed this. I will update this now. Thanks.

**Comment by Abhinav1217** [comment]
Fixed the links, I will upload png for newer version soon.
