### ISSUE TITLE
Wiki is outdated

### ISSUE THREAD

**Issue by footvaalvica** [folkswithhats/fedy#351]
The wiki is outdated and has things that don't apply to Fedy anymore. For example plugins now are a `metadata.json` file with instructions for what Fedy has to do instead of shell scripts. The information about plugins is in README.md so we could use that.

**Comment by satya164** [comment]
At the top of the WIki, it says `NOTE: These apply to an older version of Fedy and may be no longer relevant.`

**Comment by footvaalvica** [comment]
Yeah I know, I filed this as a bug so that someone would pay attention to it and maybe start rewriting it. I've started doing it.

**Comment by satya164** [comment]
Awesome!

**Comment by footvaalvica** [comment]
I have finished rewriting the plugins part of the wiki. I would like you to take a look at it and see what we could be done.
