### ISSUE TITLE
Downloading the wrong version of Sublime Text 3

### ISSUE THREAD

**Issue by lucasdiedrich** [folkswithhats/fedy#359]
For some reason, when i try to update my Sublime Text 3 fedy still downloading the version 3083, but there is already a new build 3123. I tried uninstall and installing again, uninstalling removing the cache folder and installing and still the same problem.

In the folder `/var/cache/fedy/sublimetext` i see its downloading the package `sublime_text_3_build_3083_x64.tar.bz2`

I'm running Fedy on Fedora 23 (fedy-4.1.2-1.fc23.noarch).

**Comment by Abhinav1217** [comment]
Fedy should clear the cache before downloading stuffs.  If it is not  q

**Comment by Abhinav1217** [comment]
In my tests, I did find that sometimes, fedy is not clearing its cache.  Best I could come up with is when I run fedy as root, `sudo fedy`, or in a different user account then the cache would not clear when I run it normally.

I will try to fix it before next update.

The st3 plugin is working fine as seen below, It is downloading the latest version of the sublime text 3.

```
[Abhinav@abhinav-f23 ~] $ fedy
--2016-04-26 15:14:15--  http://www.sublimetext.com/3
Resolving www.sublimetext.com (www.sublimetext.com)... 209.20.75.76
Connecting to www.sublimetext.com (www.sublimetext.com)|209.20.75.76|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 26490 (26K) [text/html]
Saving to: ‘STDOUT’

-                                100%[==========================================================>]  25.87K  36.5KB/s    in 0.7s    

2016-04-26 15:14:22 (36.5 KB/s) - written to stdout [26490/26490]

--2016-04-26 15:14:22--  http://download.sublimetext.com/sublime_text_3_build_3103_x64.tar.bz2
Resolving download.sublimetext.com (download.sublimetext.com)... 104.236.0.104
Connecting to download.sublimetext.com (download.sublimetext.com)|104.236.0.104|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7837097 (7.5M) [application/octet-stream]
Saving to: ‘sublime_text_3_build_3103_x64.tar.bz2’

sublime_text_3_build_3103_x64.ta   2%[>                                                          ] 193.73K  68.7KB/s               ^C
[Abhinav@abhinav-f23 ~] $ 
```

I can suggest a few things for now.
 

- Try manually deleting `/var/cache/fedy` folder and run fedy again.

- Check if the script `/usr/share/fedy/plugins/sublimetext.plugin\install.sh` is same as https://github.com/folkswithhats/fedy/blob/master/plugins/sublimetext.plugin/install.sh 

Let me know if it helps.

**Comment by lucasdiedrich** [comment]
Deleting the folder /var/cache/fedy didn't worked, but, after that i
checked the intall.sh file, and its not the same file from the link you
mentioned. Why is that?

Em ter, 26 de abr de 2016 às 06:56, Abhinav Kulshreshtha <
notifications@github.com> escreveu:

**Comment by Abhinav1217** [comment]
Strange?  Your fedy verson is up-to-date but why didn't the plugins update.  I will look into it. I am planning to push a new release next week.  For now, you can either reinstall fedy, or just download the newer plugin from github and replace it. Hopefully it would be fixed in next release.
