### ISSUE TITLE
Please bring back Popcorntime

### ISSUE THREAD

**Issue by andreicristianpetcu** [folkswithhats/fedy#360]
Hi,

I donwloaded PopcornTime from this [web site](https://popcorntime.sh/) on my Fedora 23 and it works. Please bring back the install button for the popcorntime app :P

Thank you

**Comment by Abhinav1217** [comment]
It is planned to have it back in next update.

**Comment by andreicristianpetcu** [comment]
Thank you! :D

**Comment by DamienCassou** [comment]
When is the next update please?
