### ISSUE TITLE
Please add terminix terminal to fedy

### ISSUE THREAD

**Issue by curantes** [folkswithhats/fedy#361]
Would be nice if the terminix terminal could be added in fedy since its fits very nice with the gnome 3 environment and sure is one of the best terminal emulators I have tested for Gnome 3.

ref: https://github.com/gnunn1/terminix

there is also already a package ready to use for it from copr:

https://copr.fedorainfracloud.org/coprs/heikoada/terminix/

**Comment by Abhinav1217** [comment]
I have used terminix about a month ago. It was quite unstable. Also, UI broke on different desktop editions of fedora. I haven't used its copr yet. We are already set for next release, so we may consider it after that. PR on the https://github.com/folkswithhats/fedy-plugins-developers would be welcomed.
