### ISSUE TITLE
Nothing is working

### ISSUE THREAD

**Issue by geek1011** [folkswithhats/fedy#366]
Almost nothing is working in the installer in Fedora 23. It just says error. It will not explain anything else.

**Comment by satya164** [comment]
@geek1011 Can you run Fedy from the Terminal and post the error messages?

**Comment by geek1011** [comment]
@satya164 Sorry, I just realized that my VM ran out of disk space. Btw, WPS office does not work right now, the download page for it does not have any link. You might want to link it directly to one of the RPMs on this page: https://web.archive.org/web/20160420051127/http://wps-community.org/downloads?vl=a20 because for some reason these links still work.
