### ISSUE TITLE
Can't install in Fedora 24

### ISSUE THREAD

**Issue by squgeim** [folkswithhats/fedy#367]
Running the script gives this error:

> Last metadata expiration check: 0:06:33 ago on Tue Jun  7 09:20:41 2016.
> Status code: 404 for http://folkswithhats.org/repo/24/RPMS/noarch/folkswithhats-release-1.0.1-1.fc24.noarch.rpm
> Installing fedy...
> Last metadata expiration check: 0:06:34 ago on Tue Jun  7 09:20:41 2016.
> No package fedy available.
> Error: Unable to find a match.

**Comment by danstewart** [comment]
They usually don't support the latest version until release.

**Comment by danstewart** [comment]
If you install the Fedora 23 rpm it works though, or at least it did for me a few weeks ago when I tried it.

**Comment by Abhinav1217** [comment]
Sorry for the delay. I caught flu. Lost track of the release date. I will update the RPM in few hours.

**Comment by Abhinav1217** [comment]
Pushed update on the server all users including F24 users should get an update in few minutes
