### ISSUE TITLE
Problems with DNF after installing Skype

### ISSUE THREAD

**Issue by WolfangAukang** [folkswithhats/fedy#368]
Hello guys,

I made a clean install of Fedora 22. When I tried to install Skype, it goes succesfully, but breaking up DNF later. When I try to use DNF, it says aborted, or it doesn't gave any response.

I found that issue at https://bugzilla.redhat.com/show_bug.cgi?id=1315811, but I cannot reproduce the solution because I have no machine to extract that (it's much easier to reinstall Fedora, than doing that).

**Comment by Abhinav1217** [comment]
They have provided a solution. You need to update dnf and rpm before installing any packages on a fresh install os. I had similar problem few year ago, caused by same mistake.
