### ISSUE TITLE
Support for f24

### ISSUE THREAD

**Issue by smekras** [folkswithhats/fedy#369]
Is there a timeframe for Fedora 24 support? I'd rather wait for fedy before I upgrade.

**Comment by hispeedzintarwebz** [comment]
In the meantime, I found it helpful to look through the plugins folder - you can read the scripts and install some of the applications/tweaks very easily.  I installed a few things to tie me over until fedy is ready for F24.

Side note, if there's anything I can do to help, please let me know.  Don't have a ton of experience, but am willing to learn and would love to contribute to one of my favorite and most-used projects.

**Comment by xasx** [comment]
I just upgraded and besides `fedy`, there's a major issue with rpmfusion, where most of the packages do not have proper pgp signatures which make upgrading them impossible (unless disabling gpgcheck).

See also [Bug 4073](https://bugzilla.rpmfusion.org/show_bug.cgi?id=4073)

The effect here (besides others): ultra-ugly font rendering :stuck_out_tongue_winking_eye:

**Comment by hispeedzintarwebz** [comment]
Hmm...looks like the fedy install script installs them by default using the nogpgcheck flag.  That's why I've never noticed this.

From fedy-installer:
```
rpm --quiet --query rpmfusion-free-release || dnf -y --nogpgcheck install http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm

rpm --quiet --query rpmfusion-nonfree-release || dnf -y --nogpgcheck install http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
```

**Comment by Abhinav1217** [comment]
Sorry for the delay. I caught flu. Lost track of the release date. I will update the RPM in few hours.

**Comment by xasx** [comment]
Should we already be able to see it in the repo?

There's no `24` folder there yet.

**Comment by xasx** [comment]
Now it's there.

Andy I have my nice fonts back again :wink:
