### ISSUE TITLE
[VSCODE] - Incorrect icon

### ISSUE THREAD

**Issue by bddenhartog** [folkswithhats/fedy#370]
Installing Visual Studio Code via Fedy results in an incorrect icon being used. This issue persists through reboots.

Prior to installing with Fedy, I had the Visual Studio Code binary downloaded and had used it previously -- it was searchable through the gnome search bar shown when the "overview" is activated. Doing this showed the proper icon.

Attached is a display of the icon in the application list. This icon is what the application is installed with, this is not simply a bug in the application list.
![fedy-vs-code-icon](https://cloud.githubusercontent.com/assets/3893293/16247415/71948960-37be-11e6-80d6-067ca0246f93.png)

**Comment by Abhinav1217** [comment]
We use Copr From Mosquito. I think he had bundled this icon with the package. It was there even when I tried it before we included in fedy.  I will try to use xdg-icon to replace this with proper one. But its not yet a high priority.

**Comment by danstewart** [comment]
[Here's one I found that works well](http://mahpahh.com/content/images/2015/05/vso.png).

```bash
cd ~/Downloads
wget http://mahpahh.com/content/images/2015/05/vso.png  
sed -i s/icon=code/icon=/home/<user>/Downloads/vso.png/g /usr/share/applications/vscode.desktop
```
