### ISSUE TITLE
Fedora 24 support

### ISSUE THREAD

**Issue by idtyu** [folkswithhats/fedy#371]
Hi:

Have been trying to use the installation script, but there is no rpm available for fedora 24, so I tried to install Fedora 23 rpm, it says that it fails to synchronize ... so I guess we need Fedora 24 support ?

**Comment by Magnus512** [comment]
We have the same problem :package: :facepunch:

**Comment by Cristoph** [comment]
+1

**Comment by ranjithsiji** [comment]
+1. I had tried the old RPM. It is working on fedora 24 . But repo gives error. Also some parts of fedy not working.

**Comment by Magnus512** [comment]
@ranjithsiji the F_23 rpm ?

**Comment by jaideepkekre** [comment]
+1

**Comment by Abhinav1217** [comment]
I got down with flu thus got delayed in pushing the update. Try it now. I updated the repos.  
I got successful install on fresh F24 and a successful update on F23. Let me know if you find any issue.

**Comment by idtyu** [comment]
it works ! big thanks to Abhinav1217! hoorah !
