### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by borowitz** [folkswithhats/fedy#372]
Trying to install Fedy on Fedora 24 and get the following error:

Status code: 404 for http://folkswithhats.org/repo/24/RPMS/noarch/folkswithhats-release-1.0.1-1.fc24.noarch.rpm

**Comment by Magnus512** [comment]
There's already an issue about it, please remit to it

**Comment by ranjithsiji** [comment]
+1

**Comment by borowitz** [comment]
@Magnus512, The other issue you're referring to is if there's a F24 support and trying some stuff with F23 packages. This issue I have is that the F24 RPM is not found (see the 404) but the script is referring to it. Imho we're talking about different issues.

**Comment by Abhinav1217** [comment]
Fedy 4.2.1 is released and repos are updated. Just checked on my F24 fresh install. It should be available to all.  I got down with flu thus got delayed in releasing the updates.
