### ISSUE TITLE
Arc Theme On Fedora 24 URL Change

### ISSUE THREAD

**Issue by jvb187** [folkswithhats/fedy#377]
Looks like the Fedora 24 repo URL is slightly different than previous versions of Fedora. 

http://download.opensuse.org/repositories/home:Horst3180/Fedora_24_standard/home:Horst3180.repo

They added '_standard'.

**Comment by satya164** [comment]
@jvb187 wanna send a PR?

**Comment by bugaevc** [comment]
If this is fixed in #378 & #379, can this issue be closed?

**Comment by bugaevc** [comment]
It seems like the URL change was reverted, i.e. we no longer have `standard` -- and it no longer works with standard. See http://download.opensuse.org/repositories/home:/Horst3180/ and http://software.opensuse.org/download.html?project=home%3AHorst3180&package=arc-theme.

Should this Fedy change be reverted too?

**Comment by satya164** [comment]
Okay, please send a PR then.

**Comment by bugaevc** [comment]
Done
