### ISSUE TITLE
The window doesn't have a title

### ISSUE THREAD

**Issue by bugaevc** [folkswithhats/fedy#380]
Despite the title being [passed](https://github.com/folkswithhats/fedy/blob/master/app.js#L32) in the code, the resulting window has no title. This results in it being titled as just "gjs" in Overview.

![image](https://cloud.githubusercontent.com/assets/10091584/16992412/dd33f44e-4ea7-11e6-9c87-769ee8314c16.png)

Tested on F23 and F24 with identical results.

GTK Inspector says that GtkApplicationWindow.title = NULL. If manually set there, it works.

![image](https://cloud.githubusercontent.com/assets/10091584/16992461/1a4cb4f6-4ea8-11e6-8c2a-5ccf9150563b.png)

I wish I knew GTK/gjs enough to understand what's going on here.

**Comment by Abhinav1217** [comment]
This is an issue since F22, I discussed it with Satya too before I started working on Fedy.  Also, It wasn't such an urgent bug because it didn't affect the functionality and interface look good without big and empty title bar.  Even GTK Inspector doesn't have it.
