### ISSUE TITLE
Bracket Repo Error

### ISSUE THREAD

**Issue by arradyscode** [folkswithhats/fedy#387]
jgillich/brackets repo is deprecated, cant install on fedora 24.
https://copr.fedorainfracloud.org/coprs/mosquito/brackets/

**Comment by danstewart** [comment]
Hey @arradyscode, the brackets plugin is part of [fedy-plugins-developers](https://github.com/folkswithhats/fedy-plugins-developers). I've put in a PR for this there https://github.com/folkswithhats/fedy-plugins-developers/pull/32.

**Comment by Abhinav1217** [comment]
New links will be updated with F25 release. Stay tune.
