### ISSUE TITLE
Please add some Descriptions to the tasks

### ISSUE THREAD

**Issue by daniel-wtd** [folkswithhats/fedy#390]
Hey, 
it would be awesome to see, what each task is doing.

For me it would be enough to see a small description like:
- enables repo xyz
- installs package 1,2,3,4

Maybe you can include some README.md from the github or so, that would be awesome :)

**Comment by satya164** [comment]
Would be great to have a details button for tasks. Wanna send a PR?

**Comment by daniel-wtd** [comment]
Hey,
I'm not so comfortable with gtk coding, but will have a look and let you know, what I can do. :)

**Comment by Abhinav1217** [comment]
If you open Fedy from command line, then activities are shown in terminal.  GJS is not easy thing to personalize.
