### ISSUE TITLE
fedy download is very insecure

### ISSUE THREAD

**Issue by genodeftest** [folkswithhats/fedy#391]
Fedy should:
1. provide a HTTPS-secured (encrypted, certified) download page for the installer script
2. the installer should keep GPG key verification enabled
3. the installer should download the rpmfusion repository files only through an encrypted connection

Unless these 3 are fixed, anybody can MITM attack any user installing fedy. This is a security risk.

**Comment by genodeftest** [comment]
This issue is also present for some plugins, e.g. the spotify plugin, which downloads another repo file from an insecure connection:
`dnf config-manager --add-repo=http://negativo17.org/repos/fedora-spotify.repo`

Most other plugins like the skype plugin or the oracle virtualbox plugin suffer this issue too.

**Comment by DominoTree** [comment]
Yes, it's important to use SSL to download the untrusted script that you're piping straight to bash as root.

**Comment by satya164** [comment]
@Abhinav1217 Did you get a chance to setup SSL on the server?

**Comment by Abhinav1217** [comment]
It will be available with next update. I am currently working on F25 release. I am worked up with lots of things at present, That's why this year, I haven't been able to provide updates as frequently as before.

**Comment by Abhinav1217** [comment]
@genodeftest  negativeo does not have https for its repo. Similarly many do not provide ssl globally, So that's beyond fedy's scope.  But we do ensure that any repo or copr we use have good reputation. Every scripts are on github under community scrutiny. 

HTTPS everywhere for fedy downloads will be ready before F25 update.

**Comment by metabsd** [comment]
It's really easy now with lets encrypt :)

**Comment by bddenhartog** [comment]
@metabsd 
> It's really easy now with lets encrypt :)

I don't think it's that simple. The source of truth for HTTPS is at the endpoint, which is _some repository outside of Fedy's control_. Fedy can't download a plugin from an HTTPS resource if there is no HTTPS resource to begin with.

**Comment by DominoTree** [comment]
Package checksums and verified signatures should mostly mitigate MITMs of this nature, along with a host of other potential vectors for attack.

**Comment by brortao** [comment]
The install script works fine without the `--nogpgcheck` option (at least for me). Is there a good reason it's there?

**Comment by Abhinav1217** [comment]
The reason `--nogpgcheck` is there because without it will not work on those systems which have been configured to mandate gpg checking. We do not provide gpg keys anymore because script is now using mostly stuffs from regular fedora and fedora fusion repos.

**Comment by Abhinav1217** [comment]
Fedora 25 release date has been moved to 22th november, This is why I will not release Fedy tonight.

**Comment by bheru27** [comment]
ssl is ready, i don't know about gpg check if should be done

**Comment by genodeftest** [comment]
GPG check would be nice because X.509 is known to be horribly broken. It happened to be possible quite often to get a Certificate for a third party website.

**Comment by andrewcole50** [comment]
Link on folkswithhats.org is now incorrect. Should read http**s**://xxxxxxx

**Comment by bheru27** [comment]
what @andrewcole50  its full https now, i'm looking to do gpg sign too

**Comment by bheru27** [comment]
on the fedy-installed too, https now

**Comment by Abhinav1217** [comment]
Fedy website has now fully on https. We can close this now. Some scripts using 3rd party links may still be on http but that is beyond our control. I don't think if there is any urgent need for gpg check at this point.

**Comment by bddenhartog** [comment]
> Fedy website has now fully on https

The accurate statement is that https is now _available_ on folkswithhats.org. To enforce HTTPS connection (which we want to do), a server block needs to be set up to redirect HTTP traffic to https. Here's an example server block that will redirect all requests made to the server to the https version of the host:

```text
server {
	listen 80 default_server;
	listen [::]:80 default_server;
	server_name _;
	return 301 https://$host$request_uri;
}
```

If you only want to handle a specific host, change the value of the `server_name` property

**Comment by bheru27** [comment]
Some people argued that such redirection was causing trouble when downloading packages, so i decided to keep it without it, the bash script does have the https tho

**Comment by genodeftest** [comment]
> I'd argue that HTTPS should be enforced, and any issues should be raised and resolved as normal.

Me too. Please enforce at least HTTPS or PGP signatures, preferably both. This bug is still fully present.

**Comment by bddenhartog** [comment]
@genodeftest, to be clear, I was talking about enforcing HTTPS across the website. There is no way for us to enforce that plugins are hosted on servers that serve over secure http.
