### ISSUE TITLE
Easy setup for Docker, KVM, Ansible.

### ISSUE THREAD

**Issue by metabsd** [folkswithhats/fedy#394]
Would be nice!

**Comment by bddenhartog** [comment]
I've created a separate issue for adding Docker support (see above). I plan to take care of this within the week.

**Comment by Abhinav1217** [comment]
I have included the re-structuring issue on my TODO list. I will work on it after stabilizing F25 release.

**Comment by Abhinav1217** [comment]
I have included the re-structuring issue on my TODO list. I will work on it after stabilizing F25 release.
