### ISSUE TITLE
Request: AMD Gpupro 

### ISSUE THREAD

**Issue by biji** [folkswithhats/fedy#396]
Please add feature to install AMD Gpupro:

http://phoronix.com/scan.php?page=news_item&px=AMDGPU-PRO-16.40-Released

**Comment by Abhinav1217** [comment]
From the website 

> The Red Hat download link can be found here with support for RHEL 7.2. **No word on whether it will work with Fedora,** but likely not if it's targeting only the RHEL7 stack.

Fedy currently targets Fedora releases as main OS.  Plus it depends on the hardware of the user. We had similar discussion for NVIDIA also, about a year ago. Drivers are hardware agnostic and can crash system if installed casually.

So at this moment, it is out of fedy's scope. Maybe in future.
