### ISSUE TITLE
Better separation of concerns for categories and applications

### ISSUE THREAD

**Issue by bddenhartog** [folkswithhats/fedy#397]
## Overview

I started using Fedy shortly after moving to Fedora over a year ago. It wasn't until a few weeks ago that I discovered [folkswithhats/fedy-plugins-developers](https://github.com/folkswithhats/fedy-plugins-developers). I'm opening this issue to gain clarity as to why the two are maintained separately, and propose a solution for absolving the need to do so. The immediate issues I see with keeping certain plugins separate from the main app repo are listed below:
- **Inaccessibility**. I can't remember exactly how I stumbled upon it, but the developer plugins repository is not made visible... anywhere, as far as I can tell.
- **Duplication**. This causes unecessary maintenance overhead. There are several plugins which exist in both repositories:
  - Atom
  - Brackets
  - Oracle JDK
  - Sublime text (although the _developers_ repo contains v2, and _this_ repo contains v3)
  - Visual Studio Code
## Proposed solution

I think using additional categories is the right solution here:
- Apps (contains standard applications, like browsers, music players, games, etc)
- Developer Apps (contains IDEs, editors, SDKs, etc - things specific to developers)
- Utilities (contains things like system libraries, e.g. `libdvdcss`, multimedia codecs, fonts, etc)
- Themes (no change in category meaning)
- Tweaks (no change in category meaning)

This will allow for easy integration of the existing `fedy-plugins-developers` plugins, and will help separate some of the overlapping categories with the current layout.

I am, of course, happy to do this myself and submit a PR -- I just wanted to see if this is something that would be beneficial/appreciated before I got started.

**Comment by satya164** [comment]
My original idea behind separating the developer plugins was they don't need to be present in the default installation of Fedy, and there could be a plugin which just installs the developer plugins. Of course it doesn't matter if they are in the same repo or separate repo. Though separate repo is easier.

I think an additional category sounds good.

**Comment by bddenhartog** [comment]
Great, I'll get a PR out to you today.

**Comment by Abhinav1217** [comment]
Added to my TODO list. I will start working on it after stabilizing F25 update.

**Comment by bddenhartog** [comment]
Re-opening this so the PR that I'll be sending through tonight links to a proper issue.
