### ISSUE TITLE
Fedora 25

### ISSUE THREAD

**Issue by ReclusiveGeek** [folkswithhats/fedy#398]
Could you please let us have a time frame for the Fedora 25 repo as its now in final freeze and due to be released on 15th November and I would like to start testing.

Many thanks for a great project.

**Comment by emelbardis** [comment]
I just upgraded to f25 beta and noticed the repo is failing. Looking forward to continued Fedy!

**Comment by Abhinav1217** [comment]
Fedy repos depend on RPMFusion repos which are not available for alpha or beta releases for fedora. If you want to test it then you need to install RPMFusion f24 repos manually in your F25 beta release and build fedy from github. 

I will try to update Fedy release by 14th november Indian Standard Time.  RPMFusion repos were few days late two time so I do accept a lot of first day complains.  I will release another update by 20th November, By then I think all links will be updated to support F25

**Comment by naimarshad** [comment]
since fedora 25 has released fedy is still unable to install on it. Hopefully there will be update soon.

**Comment by maxiiss** [comment]
Do do I

**Comment by maxiiss** [comment]
So do I !
