### ISSUE TITLE
Not installing with Fedora 25

### ISSUE THREAD

**Issue by ranjithsiji** [folkswithhats/fedy#404]
When I try to run fedy-installer on Fedora 25 it says no package available.

**Comment by simonsaysthis** [comment]
Correct. Issue was raised a while back. Project owner was to try address the issue but I think with the delayed release of F25 it might still take a while. Also waiting patiently

**Comment by kmare** [comment]
Patiently waiting as well. Although it's mainly a matter of waiting for the other repos like rpmfusion and the rest.

**Comment by shrimpster00** [comment]
What's the ETA on this?

**Comment by christianbueno1** [comment]
hello
problem in fedora 25
[http://i.imgur.com/xYRcN3C.png](url)

**Comment by jonnjonzzn** [comment]
The repo isn't updated for 25 yet...
http://folkswithhats.org/repo/

Index of /repo/

../
22/                                                24-Jun-2016 08:36                   -
23/                                                24-Jun-2016 08:36                   -
24/                                                24-Jun-2016 08:36                   -
BUILD/                                             25-Sep-2015 13:27                   -
BUILDROOT/                                         25-Sep-2015 13:27                   -
SOURCES/                                           24-Jun-2016 08:36                   -
SPECS/                                             24-Jun-2016 08:36                   -
README.md                                          24-Sep-2015 11:52                 381
build                                              24-Jun-2016 08:36                 891

**Comment by smekras** [comment]
Add me to the list of those waiting for this. F25 is just not the same without fedy.

**Comment by LonelySpooky** [comment]
> Add me to the list of those waiting for this. F25 is just not the same without fedy.
I'm in the same boat, folks.

**Comment by riginoommen** [comment]
I am also facing this issue

**Comment by kmare** [comment]
Do you guys know of any alternatives to fedy? Like postInstallerF and such

**Comment by nektwar** [comment]
Waiting :(

**Comment by ranjithsiji** [comment]
I am also waiting. As a backup plan gone to the source code and find commands which installs the software and trying them on the shell. It is really painfull. Plz do update the repo Fast. Everybody badly needs it.

**Comment by belenos** [comment]
I'm only waiting for Fedy update to install Fedora 25 on my main machine.

**Comment by erichard** [comment]
The fedora 24 repository work fine on F25. 

Create the file `/etc/yum.repos.d/folkswithhats.repo` with
```
[folkswithhats]
name=Repository for Fedy
baseurl=http://folkswithhats.org/repo/24/
enabled=1
skip_if_unavailable=1
metadata_expire=1d
gpgcheck=0
```
then `$ sudo dnf install fedy`
It work just fine. I've installed all I need without problem.

When the f25 repo will be released you will just need to update that file and change the fedora version.

**Comment by christianbueno1** [comment]
please if you know one blog or post with the step for update the file , share us the link. @erichard

**Comment by simonsaysthis** [comment]
@christianbueno1 afaik not yet. Only once the F25 version is released. I have manually installed what I need. It was actually really easy and much saver. I am sightly hesitant using the F24 version on F25 with Wayland, especially the tweaks

**Comment by simonsaysthis** [comment]
Have you guys heard of Korora? Its like a Fedora remix with tons of tweaks and all the software you would get through a tool like Fedy. If you on Korora 24 you can upgrade to Korora 25 and everything works perfect. No need for tweaks, codec etc

**Comment by Boricua3** [comment]
Count me among those waiting for Fedora 25 Fedy.

**Comment by jonnjonzzn** [comment]
If this project has been abandoned I'll fork it and put a new infrastructure in place.  I won't be able to get to it until over Christmas Break though.  If we don't hear something soon I'll at least promise to have a working alternative up by year's end.

Mike

**Comment by dworzanski** [comment]
I [asked the maintainer on Twitter](https://twitter.com/Dworzanski/status/801223766219096064) about an update for Fedora 25 a week ago. [He said](https://twitter.com/satya164/status/801370102318907393) to check the GitHub repo. Now that a week has passed, I [asked him](https://twitter.com/Dworzanski/status/803620756865384449) if he has abandoned the project. Waiting for a reply.

**Comment by dworzanski** [comment]
The maintainer has been completely unresponsive for a couple days. I've [asked the original author](https://twitter.com/Dworzanski/status/804471170728939520) if he'd be willing to intervene to save Fedy.

I think Fedy needs a new maintainer who is able to be responsible and responsive. Personally, JS is not my primary language so I would probably not do as good a job as someone who uses JS regularly. I think it'd be better to save this repo (and all the assets that have been built) rather than doing a complete fork and starting from scratch.

**Comment by satya164** [comment]
I don't have access to the server where Fedy repository is hosted currently, but I could help setup a new server if someone volunteers. I made this repo into an organisation hoping that there could be bunch of people who can help maintain Fedy. @Abhinav1217 has been doing his best, but it's really difficult for one person.

**Comment by ml2mst** [comment]
The new maintainer wrote this on G+

> Abhinav Kulshreshtha
> 24 nov. 2016+
> Fedy will be released within next two days. I got an unexpected interruption.

I hope it isn't a serious (family) matter.

**Comment by bddenhartog** [comment]
The great thing about open source software is thay _everybody_ can contribute. The great thing about Linux based operating systems is that there's generally only one way to do something (like install packages). 

If you did a clean installation of F25 and are missing all of your software, it's easy enough to manually run the commands that Fedy runs when you click the button. Simply view the source code for the plugins you want, and run the commands it runs.

If you want to use the graphical interface, you can either wait for the repo to be updated, or ask how you can help contribute, and reduce the work piled on one person's shoulders.

**Comment by satya164** [comment]
If someone wants to help, feel free to ping me.

**Comment by bheru27** [comment]
@satya164  I want to help :) what can i do?

**Comment by satya164** [comment]
@bheru27 It's late here, so let's talk tomorrow? Ping me on telegram/messenger/twitter or give me your telegram username and I'll ping you.

**Comment by bheru27** [comment]
@satya164 sure, its bheru27, in both telegram and twitter, good night!

**Comment by JeffreyVdb** [comment]
I'm willing to help as well. I'm a quick learner so I don't think it should be a big problem for me with a short explanation

**Comment by satya164** [comment]
@JeffreyVdb can you give your telegram username as well?

**Comment by ranjithsiji** [comment]
I any plan to create a F25 repo? Is you people working on this ?

**Comment by haeringer** [comment]
@satya164 I'd like to help, too, if there's still any need.

**Comment by satya164** [comment]
@bheru27 is on it. but I invited you to the telegram group in case help is needed :D

**Comment by downeym** [comment]
Big thanks everyone for helping out :-) it will be great to get Fedy back and running!

**Comment by bheru27** [comment]
Yeah sorry, some stuff with nginx doing redirects 😅 sorry for all problems

**Comment by bheru27** [comment]
Its done :D

**Comment by bheru27** [comment]
Welp, the f25 repo is there, I'll close this
