### ISSUE TITLE
Add Firefox Nightly

### ISSUE THREAD

**Issue by barrosgeraldo** [folkswithhats/fedy#405]
Ideia: https://www.mozilla.org/en-US/firefox/developer/

**Comment by stonehellway** [comment]
The installation of Firefox Dev edition is pretty straightforward. You download the *.tar un untar it. Then you can launch the ./firefox file directly from the folder.

**Comment by satya164** [comment]
You can create your own plugins and place them under `~/.local/share/fedy/plugins`

**Comment by danstewart** [comment]
There is a PR for this on the dev repo:
https://github.com/folkswithhats/fedy-plugins-developers/pull/30

**Comment by bddenhartog** [comment]
@danstewart given that #416 will be merged in at the `fedy-plugins-developers` repo will be deprecated, I think it makes sense to keep this issue here (saves me time migrating issues :thumbs-up:)

**Comment by danstewart** [comment]
Just noting that for the firefox built in updates to work after install we'll have to `chown` the install dir.
There was a PR on the dev repo but it's been deleted now so it will have to be readded here.

Is this something we want in the core plugins list or should it just be saved for the community plugins?

**Comment by barrosgeraldo** [comment]
Just one update here, Firefox Developer Edition is merged with Firefox Nightly, so is cool work to add this here, and yes, to install is need download from oficial website because Firefox Nightly is a pre release version and is updated everyday while the developers work with it daily.

https://www.mozilla.org/firefox/channel/desktop/
