### ISSUE TITLE
301 Moved Permanently

### ISSUE THREAD

**Issue by bidzapfc** [folkswithhats/fedy#411]
Fresh install of Fedora 25 today and this happens:

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0   1623      0 --:--:-- --:--:-- --:--:--  1618
./fedy-installer: line 1: html: No such file or directory
./fedy-installer: line 2: syntax error near unexpected token `<'
'/fedy-installer: line 2: `<head><title>301 Moved Permanently</title></head>

It is weird, because I installed  it yesterday without any problems

**Comment by bidzapfc** [comment]
But I downloaded script from this github and ran it, it worked

**Comment by bheru27** [comment]
Well fuck, i messed up the https website, i'll check what's going on

**Comment by cavalor** [comment]
I have the same isue on Fedora 25.

**Comment by bheru27** [comment]
Un your folswithhat .repo file change http for https

**Comment by bheru27** [comment]
Folkswithhats*
