### ISSUE TITLE
spotify crashes

### ISSUE THREAD

**Issue by stanfieldr** [folkswithhats/fedy#412]
I am running a fresh install of Fedora 25. Starts up fine. When I type my username/password, it crashes upon submission.

```bash
[robert@robert-desktop applications]$ spotify 
spotify: /lib64/libssl.so.1.0.0: no version information available (required by spotify)
spotify: /lib64/libcrypto.so.1.0.0: no version information available (required by spotify)
spotify: /lib64/libcurl.so.4: no version information available (required by spotify)
/usr/lib64/spotify-client/spotify: /lib64/libssl.so.1.0.0: no version information available (required by /usr/lib64/spotify-client/spotify)
/usr/lib64/spotify-client/spotify: /lib64/libcrypto.so.1.0.0: no version information available (required by /usr/lib64/spotify-client/spotify)
/usr/lib64/spotify-client/spotify: /lib64/libcurl.so.4: no version information available (required by /usr/lib64/spotify-client/spotify)
[1223/015123:ERROR:main_delegate.cc(752)] Could not load cef_extensions.pak
/proc/self/exe: /lib64/libssl.so.1.0.0: no version information available (required by /proc/self/exe)
/proc/self/exe: /lib64/libcrypto.so.1.0.0: no version information available (required by /proc/self/exe)
/proc/self/exe: /lib64/libcurl.so.4: no version information available (required by /proc/self/exe)
[1223/015123:ERROR:main_delegate.cc(752)] Could not load cef_extensions.pak
[1223/015147:ERROR:PlatformKeyboardEvent.cpp(94)] Not implemented reached in static bool blink::PlatformKeyboardEvent::currentCapsLockState()
Segmentation fault (core dumped)
```

**Comment by imgglasses** [comment]
I'm experiencing the same as @stanfieldr . Exact same error. Any ideas how to solve this? or go around this?

**Comment by bddenhartog** [comment]
I'm unable to recreate this on a new F25 installation. 

Please provide the output of the following commands:

* `uname -a`
* `dnf installed libcurl-compat`
* `which spotify`
* `cat /usr/bin/spotify`

**Comment by stanfieldr** [comment]
I just reproduced this after reformatting the Mac Air with F25. My desktop had F25 installed via a reformat as well.

uname -a
```
Linux robert-air 4.8.15-300.fc25.x86_64 #1 SMP Thu Dec 15 23:10:23 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
which  spotify
```
/usr/bin/spotify
```
cat /usr/bin/spotify | head -n1
```
ELF>�PZ@p�p@8
```
ls -l /usr/bin/ | grep spotify
```
lrwxrwxrwx.   1 root root          33 Dec 21 17:07 spotify -> /usr/lib64/spotify-client/spotify
```

The package libcurl-compat doesn't exist.

**Comment by bheru27** [comment]
@stanfieldr search it with "dnf search libcurl" see what you need, install it and see if it works, give feedback so it gets changed :)

**Comment by bddenhartog** [comment]
@stanfieldr Did you close this issue because installing libcurl resolved the issue, or simply because the PR was closed?

I want to make sure we keep issues open until a solution is provided.

**Comment by stanfieldr** [comment]
Just because the PR was closed. Also noticed would need compat-openssl which is in the repo the spotify plugin is currently using now in order for my PR to work. And there was a good point about being able to update via dnf update, so I just went ahead and closed it lol

**Comment by bddenhartog** [comment]
@stanfieldr Right - I agree with the reasoning behind closing the PR, but it sounds like this issue is still valid until a solution is available :P

**Comment by Abhinav1217** [comment]
Can someone confirm this issue is not due to wayland being default in Fedora 25 Gnome shell.   So far for me Spotify is working in non gnome spins, but crashing in Gnome wayland. https://wiki.gnome.org/Design/OS/MessageTray/Compatibility does not list spotify as issue, in wayland because legacy tray is not supported, a lot of my apps are randomly crashing in wayland.

**Comment by stanfieldr** [comment]
I can confirm it crashes on X with Gnome

**Comment by Abhinav1217** [comment]
A thought to think about !!  Just found out that Spotify is now in fedora repos from Fedora 25, It does not have any issues in any spin, or in wayland.

Our script uses installation from http://negativo17.org/ which is, on my tests, showing issues on wayland on Fedora 25, working with few random crashes in F25 gnome x.org, and working with no issues in other F25 spins and F24 gnome-x.org . 

How about we use official repos for F25 and negativo repos for F24 and below.

**Comment by danstewart** [comment]
Negativo one is working for me now.

**Comment by Abhinav1217** [comment]
@danstewart  Even on wayland?

**Comment by danstewart** [comment]
@Abhinav1217 is there any way to check other than the gear on the log in page? The log in page shows Gnome, not Gnome Xorg.

**Comment by bddenhartog** [comment]
I'll have a PR out for this in a bit, wrapping some things up this evening. I had some surprise car trouble that ate up a day this weekend :1st_place_medal:

@Abhinav1217 @danstewart I ran a semiautomated test suite to install every plugin and fail if any fail to install. I had a few, but they are the same that fail to install when running via the GUI. I'm going to be working on building a travis.ci-friendly dockerized test so we don't need to test the core functionality of PRs, but implementing this may be done better (read: more sanely, without relying on external network connections) may require a bit more than I'm initially estimating I'll be able to devote to it over the next few weeks.

**Comment by danstewart** [comment]
@bddenhartog Let me know if I can do anything to help, don't have much experience with that though.

**Comment by bddenhartog** [comment]
@danstewart will do - thanks for the offer!

**Comment by Abhinav1217** [comment]
@danstewart There should be three option, Gnome, Gnome Classic, Gnome on XOrg. Choose Gnome on XOrg, If you can see notification icon tray in the bottom left corner, It is XOrg.

**Comment by danstewart** [comment]
Closing. Just tested in a VM and it works fine on both Wayland and XOrg.

Looks like there is an issue with the settings page - but that's obviously nothing to do with us.
