### ISSUE TITLE
Add powerline

### ISSUE THREAD

**Issue by bddenhartog** [folkswithhats/fedy#427]
Add a plugin for `powerline`, and set all users (including `root`) up with a default configuration.

**Comment by Abhinav1217** [comment]
F25 comes with powerline preconfigured. Do we still need this plugin?

**Comment by Abhinav1217** [comment]
Closing this issue as discussion can be done on the PR itself.

**Comment by bddenhartog** [comment]
> Closing this as discussion is being done on PR itself.

This is not why issues should be closed. Issues should be closed when the solution is merged, and that happens automatically when the pull request is approved and merged in with an appropriate `Closes #X` message.

Discussion around the _why_ happens in the issue. PR comments should strictly be about the _how_, or implementation -- more specifically, about adjustments to how the contributor implemented the solution.

**Comment by Xmetalfanx** [comment]
Big fan of Fedy here ... posting this here just for now as I saw the Fedora team itself post these instructions 

https://fedoramagazine.org/add-power-terminal-powerline/

I have read a few things where "you want to check if another user is using Powerline so their configuration doesn't get messed up, with a second user's uninstall of Powerline" ... yeah logically that does make sense

**Comment by danstewart** [comment]
Closing. See full discussion on #382 

@bddenhartog 
> This is a good idea, and when I finish the major rework to Fedy's internal structure, we'll have a "community repository" -- a centralized location for user-submitted plugins. These will show up in the app like existing plugins, and this would be a great place for installing Powerline and providing a basic preconfigured environment.
