### ISSUE TITLE
Replace Jetbrains applications with Jetbrains Toolbox App

### ISSUE THREAD

**Issue by delphiki** [folkswithhats/fedy#428]
As mentioned in PR https://github.com/folkswithhats/fedy/pull/425, the following apps' plugins will be removed from fedy in favor of the new [JetBrains Toolbox App](https://www.jetbrains.com/toolbox/app/) plugin, which makes it a lot easier to manage the JetBrains apps:
* clion.plugin
* intellijideacommunity.plugin
* intellijideaultimate.plugin
* phpstorm.plugin
* pycharmcommunity.plugin
* pycharmprofessional.plugin
* rubymine.plugin
* webstorm.plugin

**Comment by Abhinav1217** [comment]
Closing this as discussion is being done on PR itself.

**Comment by bddenhartog** [comment]
> Closing this as discussion is being done on PR itself.

This is not why issues should be closed. Issues should be closed when the solution is merged, and that happens automatically when the pull request is approved and merged in with an appropriate `Closes #X` message.
