### ISSUE TITLE
Add the "Adapta" theme by tista500

### ISSUE THREAD

**Issue by dralley** [folkswithhats/fedy#432]
https://github.com/adapta-project/adapta-gtk-theme

Optional wallpapers: https://github.com/adapta-project/adapta-backgrounds

COPR available here: https://copr.fedorainfracloud.org/coprs/heikoada/gtk-themes/

**Comment by dralley** [comment]
Note that the COPR also includes the Arc and Paper themes

**Comment by danstewart** [comment]
I wish I knew about the copr before I installed it manually yesterday.
I'll get this added tomorrow.

**Comment by danstewart** [comment]
Looks like the copr is currently failing for adapta:
https://copr.fedorainfracloud.org/coprs/heikoada/gtk-themes/package/adapta-gtk-theme/

I'll try adding a plugin to add it manually.

**Comment by danstewart** [comment]
@dralley Building manually takes a while so talking to the others about what we should do with this.
I've got a working install script if you want it though.
Gist: [adapta-gtk-theme-install.sh](https://gist.github.com/danstewart/179ca94277a3a6a4147b5709dec21602)

**Comment by bddenhartog** [comment]
@danstewart any update on this?

**Comment by danstewart** [comment]
@bddenhartog Not sure if I'm being an idiot but for some reason I can't install it from the [copr](https://copr.fedorainfracloud.org/coprs/heikoada/gtk-themes/):

```
$ sudo dnf copr enable heikoada/gtk-themes

You are about to enable a Copr repository. Please note that this
repository is not part of the main distribution, and quality may vary.

The Fedora Project does not exercise any power over the contents of
this repository beyond the rules outlined in the Copr FAQ at
<https://docs.pagure.org/copr.copr/user_documentation.html#what-i-can-build-in-copr>,
and packages are not held to any quality or security level.

Please do not file bug reports about these packages in Fedora
Bugzilla. In case of problems, contact the owner of this repository.

Do you want to continue? [y/N]: y
Repository successfully enabled.

$ sudo dnf install adapta-gtk-theme
Last metadata expiration check: 0:00:00 ago on Sat 28 Oct 2017 18:40:06 BST.
  * Maybe you meant: adapta-gtk-theme
No match for argument: adapta-gtk-theme
Error: Unable to find a match
```


I still have the manual script in a [gist](https://gist.github.com/danstewart/179ca94277a3a6a4147b5709dec21602) if you'd rather I just add that?

**Comment by bddenhartog** [comment]
@danstewart You should see various results after searching for `adapta`:

```
$ dnf search adapta-gtk
=================================== Name Matched: adapta-gtk ===================================
adapta-gtk-theme.src : An adaptive Gtk+ theme based on Material Design Guidelines
adapta-gtk-theme-gtk2.noarch : Adapta GTK+2 themes
adapta-gtk-theme-gtk3.noarch : Adapta GTK+3 themes
adapta-gtk-theme-gtk4.noarch : Adapta GTK+4 themes
adapta-gtk-theme-gedit.noarch : Adapta gEdit theme
adapta-gtk-theme-plank.noarch : Adapta Plank themes
adapta-gtk-theme-xfwm4.noarch : Adapta Xfwm4 themes
adapta-gtk-theme-chrome.noarch : Adapta Chrome(ium) themes
adapta-gtk-theme-common.noarch : Files common to Adapta themes
adapta-gtk-theme-openbox.noarch : Adapta openbox themes
adapta-gtk-theme-cinnamon.noarch : Adapta Cinnamon themes
adapta-gtk-theme-metacity.noarch : Adapta Metacity themes
adapta-gtk-theme-xfce4-notifyd.noarch : Adapta Xfce4 notifyd theme
```

I'm unsure of the details of the copr repo, but it would seem like the author publishes themes under a different name than what is listed on the COPR web page.
