### ISSUE TITLE
Readme needs updated installation instructions

### ISSUE THREAD

**Issue by RafalSkolasinski** [folkswithhats/fedy#439]
A installation [script](https://www.folkswithhats.org/fedy-installer) seems unavailable
```
An error occurred.

Sorry, the page you are looking for is currently unavailable.
Please try again later.

If you are the system administrator of this resource then you should check the error log for details.

Faithfully yours, nginx.
```

**Comment by bddenhartog** [comment]
Where are you encountering this? The script is simply named `installer`, not `fedy-installer` like the URI you linked to. Follow the installation instructions on www.folkswithhats.org should result in a successful installation.

**Comment by RafalSkolasinski** [comment]
seems like link in readme: https://github.com/folkswithhats/fedy/blob/master/README.md#installation is out of date

**Comment by bddenhartog** [comment]
Thanks @RafalSkolasinski. I'll get the readme updated shortly (really, it should just direct users to the website).

**Comment by RafalSkolasinski** [comment]
No problem!
