### ISSUE TITLE
Better font rendering conflicts with Fedora 26

### ISSUE THREAD

**Issue by evfool** [folkswithhats/fedy#450]
Hi,
In the weekend I have upgraded my installation to Fedora26 (development version, not released yet), and the setup broke, I did not even get to the login screen, and even the console seemed to freeze after a certain time. After several restarts 
* I have found references to harfbuzz missing symbols (`/usr/lib/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates`), 
* googling for the undefined symbol got me to a fix for archLinux (https://gist.github.com/cryzed/e002e7057435f02cc7894b9e748c5671)
* removing the freetype-freeworld package installed by fedy with the better font rendering got me to a working desktop again.
I'm not sure if it is possible to handle this in Fedy, but it would be nice not to break GUI after F26 comes out (but maybe the installation won't fail, the problem might be simply because of the sysupgrade scenario, in which case you can close this as a wontfix)

I have also seen #149, but based on the arch-related gist, fontconfig ultimate suffers from the same problem.

**Comment by Abhinav1217** [comment]
Fedora 26 is in development version, there may be some issue regarding incompatible libraries. I will look into the arclinux gist. I would give a few more days for the fedora to stabilise a little more,

**Comment by evfool** [comment]
Understood, and agreed, that it might not be stable enough, just wanted to raise awareness in any case.

**Comment by biggestchops** [comment]
Hello, I ran the upgrade from f25 to f26 last night, had the same issue (the harfbuzz thing). I didn't even think that it might have something to do with fedy, and I nuked and paved it today, so unfortunately can't provide any log files or anything. 

Can't wait for the f26 compatible version of fedy, keep up the great work!

**Comment by Abhinav1217** [comment]
Release is now done by @bddenhartog . He will release later this week last time we talked.
I just installed a fresh install of fedora and fedy. everything is working fine up untill now. Still a few things left in queue.

**Comment by bddenhartog** [comment]
To follow up on this, my workstation is currently out of commission (recently moved, local ISP booked up). I should be able to catch up with everything by tomorrow morning.

**Comment by bddenhartog** [comment]
This should be resolved with the dependency switch from `freetype-freeworld` to `freestyle`.

Please comment on this issue again if you run into any issues.
