### ISSUE TITLE
Use Sublime Text repos

### ISSUE THREAD

**Issue by stephenfin** [folkswithhats/fedy#456]
**Note:** This might already be resolved: it's Friday and I haven't checked.

It seems that with the latest release of Sublime Text, there are now [repositories](https://www.sublimetext.com/docs/3/linux_repositories.html#dnf) for Fedora. We should probably be simply enabling these and installing from there.

**Comment by bddenhartog** [comment]
> Note: This might already be resolved: it's Friday and I haven't checked.

The installation script(s) have not been updated. Thank you for bringing this to our attention.

**Comment by bheru27** [comment]
I havent checked but the install repos they do are for 64 bit version, then we should see if they dont provide 32bits ones so just modify the script to use the repo in case the computer is 64 bits.

**Comment by bheru27** [comment]
okay i just installed the thing in my computer, iit is sublime text 3, but the package doesnt say an specific version:
Name        : sublime-text
Version     : 3126
Release     : 1
From repo   : sublime-text
Summary     : Sublime Text is a sophisticated text editor for code, markup and prose
URL         : https://www.sublimetext.com
License     : Proprietary
I saw that there are the repos:
https://download.sublimetext.com/rpm/stable/i386/sublime-text.repo for i386
and https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo for x86_64, so its matter of updating the script of sublime text 3.

**Comment by Abhinav1217** [comment]
Submitted a PR which solves this. Can be closed once PR is merged.

**Comment by bddenhartog** [comment]
Closed in 0095bab5.
