### ISSUE TITLE
Add Google Play Music Desktop Player

### ISSUE THREAD

**Issue by WolfangAukang** [folkswithhats/fedy#460]
This is a desktop player for Google Play Music, which is more customizable and it's more lightweight compared to using it on web. It has RPMs available for 32 and 64 bit, and it has a MIT license.

https://www.googleplaymusicdesktopplayer.com/

**Comment by Abhinav1217** [comment]
It is now available in PR. Will be pushed soon.

**Comment by bddenhartog** [comment]
@Abhinav1217, please *do not* close issues until they are _actually resolved_.

**Comment by bddenhartog** [comment]
Closed in 0095bab5.
