### ISSUE TITLE
feddy can't install

### ISSUE THREAD

**Issue by sivapooja** [folkswithhats/fedy#463]
[siva@fedora25 ~]$ sudo sh -c 'curl https://www.folkswithhats.org/installer | bash'
[sudo] password for siva: 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   985  100   985    0     0    723      0  0:00:01  0:00:01 --:--:--   723
Adding repositories...
Last metadata expiration check: 0:00:00 ago on Wed 12 Jul 2017 06:42:09 PM.
[MIRROR] folkswithhats-release-1.0.1-1.fc26.noarch.rpm: Status code: 404 for https://www.folkswithhats.org/repo/26/RPMS/noarch/folkswithhats-release-1.0.1-1.fc26.noarch.rpm
[FAILED] folkswithhats-release-1.0.1-1.fc26.noarch.rpm: Status code: 404 for https://www.folkswithhats.org/repo/26/RPMS/noarch/folkswithhats-release-1.0.1-1.fc26.noarch.rpm
Status code: 404 for https://www.folkswithhats.org/repo/26/RPMS/noarch/folkswithhats-release-1.0.1-1.fc26.noarch.rpm
Last metadata expiration check: 0:00:05 ago on Wed 12 Jul 2017 06:42:09 PM.
rpmfusion-free-release-26.noarch.rpm             12 kB/s |  20 kB     00:01    
Dependencies resolved.
================================================================================
 Package                      Arch         Version     Repository          Size
================================================================================
Installing:
 rpmfusion-free-release       noarch       26-1        @commandline        20 k

Transaction Summary
================================================================================
Install  1 Package

Total size: 20 k
Installed size: 8.7 k
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                        1/1 
  Installing       : rpmfusion-free-release-26-1.noarch                     1/1 
  Verifying        : rpmfusion-free-release-26-1.noarch                     1/1 

Installed:
  rpmfusion-free-release.noarch 26-1                                            

Complete!
RPM Fusion for Fedora 26 - Free - Updates       1.2 kB/s | 1.7 kB     00:01    
RPM Fusion for Fedora 26 - Free                 995 kB/s | 519 kB     00:00    
Last metadata expiration check: 0:00:00 ago on Wed 12 Jul 2017 06:42:36 PM.
rpmfusion-nonfree-release-26.noarch.rpm          11 kB/s |  20 kB     00:01    
Dependencies resolved.
================================================================================
 Package                        Arch        Version     Repository         Size
================================================================================
Installing:
 rpmfusion-nonfree-release      noarch      26-1        @commandline       20 k

Transaction Summary
================================================================================
Install  1 Package

Total size: 20 k
Installed size: 8.8 k
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                        1/1 
  Installing       : rpmfusion-nonfree-release-26-1.noarch                  1/1 
  Verifying        : rpmfusion-nonfree-release-26-1.noarch                  1/1 

Installed:
  rpmfusion-nonfree-release.noarch 26-1                                         

Complete!
Installing fedy... RPM Fusion for Fedor  0% [                    ] ---  B/s |   RPM Fusion for Fedora 26 - Nonfree - Updates    896  B/s | 1.2 kB     00:01    
RPM Fusion for Fedora 26 - Nonfree              166 kB/s | 158 kB     00:00    
Last metadata expiration check: 0:00:00 ago on Wed 12 Jul 2017 06:43:01 PM.
No package fedy available.
Error: Unable to find a match
FAILED
Please report bugs at https://github.com/folkswithhats/fedy/issues

**Comment by bddenhartog** [comment]
You are attempting to download Fedy in Fedora version 26; we have not yet released an F26-compatible client. Please track #458 for this. 

On a side note, your machine's hostname is `fedora25`. This is likely to cause some confusion, as you are not running that version!
