### ISSUE TITLE
Skype should require a 64-bit machine

### ISSUE THREAD

**Issue by blackjackshellac** [folkswithhats/fedy#467]
But fedy is still installing the i686 version.

https://www.skype.com/en/download-skype/skype-for-linux/

**Comment by bddenhartog** [comment]
To clarify:

As of July 1, 2017, Microsoft has retired all Skype for Linux clients version 4.3 and older, which was previously a 32-bit client. "Skype for Linux", as of July 1 2017, is now the only client supported by Microsoft -- and it is _only_ available as a 64-bit client.

Therefore, the skype plugin should be refactored to prevent installation if the host machine is 32-bit.
