### ISSUE TITLE
SSL errors when trying to install

### ISSUE THREAD

**Issue by lwslade** [folkswithhats/fedy#468]
When opening https://www.folkswithhats.org/, my web browser gives me an SSL certificate error. I also get this error when trying to run the install script manually:

`Adding repositories...
Last metadata expiration check: 0:12:43 ago on Mon 17 Jul 2017 11:25:08 PM EDT.
[MIRROR] folkswithhats-release-1.0.1-1.fc26.noarch.rpm: Curl error (51): SSL peer certificate or SSH remote key was not OK for https://www.folkswithhats.org/repo/26/RPMS/noarch/folkswithhats-release-1.0.1-1.fc26.noarch.rpm [Unable to communicate securely with peer: requested domain name does not match the server's certificate.]
[FAILED] folkswithhats-release-1.0.1-1.fc26.noarch.rpm: Curl error (51): SSL peer certificate or SSH remote key was not OK for https://www.folkswithhats.org/repo/26/RPMS/noarch/folkswithhats-release-1.0.1-1.fc26.noarch.rpm [Unable to communicate securely with peer: requested domain name does not match the server's certificate.]
Curl error (51): SSL peer certificate or SSH remote key was not OK for https://www.folkswithhats.org/repo/26/RPMS/noarch/folkswithhats-release-1.0.1-1.fc26.noarch.rpm [Unable to communicate securely with peer: requested domain name does not match the server's certificate.]
Installing fedy...
Last metadata expiration check: 0:12:44 ago on Mon 17 Jul 2017 11:25:08 PM EDT.
No package fedy available.
Error: Unable to find a match
rm: cannot remove 'fedy-installer': No such file or directory
`

**Comment by lwslade** [comment]
I didn't notice until now that there's a separate repository for the fedy website -- my apologies if this issue is mis-filed with the wrong project.

**Comment by bddenhartog** [comment]
@lwslade Thank you for the report. This was due to misconfiguration of the CDN; it has since been resolved. It should propagate throughout the world within 15 minutes, but feel free to let me know if you still have errors connecting.

**Comment by bddenhartog** [comment]
Additionally, the issue preventing the non-www version of the domain from redirecting users to the www-version of the domain has been resolved, and should propagate within 15 minutes.
