### ISSUE TITLE
DNF Repo is not responding

### ISSUE THREAD

**Issue by NotoriousGNU** [folkswithhats/fedy#477]
My friend had an issue migrating from f25 to f26 because her fedy was unable to synchronize on DNF. Upon further investigation, I can't update fedy either from f25. I removed fedy and re-ran the installation script from the website to no avail.

I noticed you asked the guy from #459 to give you the content of `/etc/yum.repos.d/folkswithhats.repo`.

```
cat /etc/yum.repos.d/folks-with-hats.repo 
[folkswithhats]
name=Folks With Hats
baseurl=https://dl.folkswithhats.org/fedora/$releasever/
enabled=1
metadata_expire=1d
gpgcheck=0
```
Should i `mv folks-with-hats.repo folkswithhats.repo`?
Also, https://dl.folkswithhats.org/fedora/25 and 26 links to nothing; the server itself doesn't respond.

Thanks for your work and support. I hope your move went well.

**Comment by bddenhartog** [comment]
There was a temporary issue with object permissions during a background server move. This should be resolved, and re-running the command available at www.folkswithhats.org should result in a successful installation.

You shouldn't have to manually move the repo file; that name change (from `folkswithhats.fepo` to `folks-with-hats.repo`) is purely cosmetic (and is actually reverted in `folkswithhats-release@3.0.0-1`)

**Comment by bddenhartog** [comment]
Actually, _now_ it should be resolved. My apologies :)

**Comment by naimarshad** [comment]
Mannually running this command have below output.
sudo dnf -y --nogpgcheck install \                                                        1 ↵  195  22:24:25 
                "https://dl.folkswithhats.org/fedora/${releaseVersion}/RPMS/noarch/folkswithhats-release-3.0.0-1.noarch.rpm"

Last metadata expiration check: 0:09:03 ago on Mon 24 Jul 2017 10:15:23 PM +03.
[MIRROR] folkswithhats-release-3.0.0-1.noarch.rpm: Curl error (6): Couldn't resolve host name for https://dl.folkswithhats.org/fedora//RPMS/noarch/folkswithhats-release-3.0.0-1.noarch.rpm [Could not resolve host: dl.folkswithhats.org]
[FAILED] folkswithhats-release-3.0.0-1.noarch.rpm: Curl error (6): Couldn't resolve host name for https://dl.folkswithhats.org/fedora//RPMS/noarch/folkswithhats-release-3.0.0-1.noarch.rpm [Could not resolve host: dl.folkswithhats.org]
Curl error (6): Couldn't resolve host name for https://dl.folkswithhats.org/fedora//RPMS/noarch/folkswithhats-release-3.0.0-1.noarch.rpm [Could not resolve host: dl.folkswithhats.org]

**Comment by bddenhartog** [comment]
@naimarshad depending on where you're at in the world, the fix may not have propagated to you by the time I left my last comment.  Can you try again?

**Comment by naimarshad** [comment]
It is still the same..
