### ISSUE TITLE
Fedy's website is down

### ISSUE THREAD

**Issue by HenriqueCSJ** [folkswithhats/fedy#481]
Looks like a hosting problem?

**Comment by bddenhartog** [comment]
This is due to the registration expiring, not an issue with the DNS or hosting:

https://who.is/whois/folkswithhats.org

/cc @satya194

**Comment by cowboysmall** [comment]
Site is back up, but still a problem with the installer:

> [MIRROR] folkswithhats-release-3.0.0-1.noarch.rpm: Curl error (6): Couldn't resolve host name for https://dl.folkswithhats.org/fedora/26/RPMS/noarch/folkswithhats-release-3.0.0-1.noarch.rpm [Could not resolve host: dl.folkswithhats.org]
> [FAILED] folkswithhats-release-3.0.0-1.noarch.rpm: Curl error (6): Couldn't resolve host name for https://dl.folkswithhats.org/fedora/26/RPMS/noarch/folkswithhats-release-3.0.0-1.noarch.rpm [Could not resolve host: dl.folkswithhats.org]
> Curl error (6): Couldn't resolve host name for https://dl.folkswithhats.org/fedora/26/RPMS/noarch/folkswithhats-release-3.0.0-1.noarch.rpm [Could not resolve host: dl.folkswithhats.org]

Is this just a propagation issue? Or a problem with the zone files?

**Comment by bddenhartog** [comment]
@cowboysmall the zone files and file hierarchy haven't changed. I would guess you're experiencing a propagation issue.

You could also try clearing your DNS cache.
