### ISSUE TITLE
Add Brave Browser?

### ISSUE THREAD

**Issue by andrewcole50** [folkswithhats/fedy#482]
Would there be any interest or would the project be able to add the Brave Browser to FEDY? 

https://github.com/brave/browser-laptop/blob/master/docs/linuxInstall.md#fedora-x86_64

**Comment by Abhinav1217** [comment]
@bddenhartog I started working on it.  Will send a PR soon.

**Comment by Abhinav1217** [comment]
Submitted a PR on this.

**Comment by bddenhartog** [comment]
@Abhinav1217 If you put the issue number in the body of the pull request when it's created, GitHub will automatically put a "<Author> referenced this issue in <Pull Request>" link, like we see above.

I updated your PR message [here](https://github.com/folkswithhats/fedy/pull/484#issue-253229118) and removed your earlier comment in this thread to accomplish that.
