### ISSUE TITLE
FR: Please add OnlyOffice

### ISSUE THREAD

**Issue by daniel-wtd** [folkswithhats/fedy#483]
OnlyOffice seems to have good support for fedora.
Maybe you can have a look at it or add it :)

https://www.onlyoffice.com/

Best regards!

**Comment by Abhinav1217** [comment]
Its open source (GPL3) and has an official update channel for RHEL derivatives. I have installed it on test machines and if all works well I will send a PR soon.

**Comment by bddenhartog** [comment]
Closed by #577
