### ISSUE TITLE
Master PDF editor does not download

### ISSUE THREAD

**Issue by gitgt** [folkswithhats/fedy#485]
Master PDF editor does not seem to download. Console shows:
http://get.code-industry.net/public/master-pdf-editor-4.2.70_qt5.x86_64.rpm
and stays like that. Manual download works.

**Comment by danstewart** [comment]
Fix merged #494

**Comment by rishadfb** [comment]
It's broken again. Doesn't install for me.

**Comment by sudoforge** [comment]
@rishadfb I've created a new issue for this problem: #592
