### ISSUE TITLE
Mouse acceleration plugin messes up mouse hotplug & suspend resume on F26

### ISSUE THREAD

**Issue by gombosg** [folkswithhats/fedy#533]
[xorg-withfedy-mouseaccel.txt](https://github.com/folkswithhats/fedy/files/1290558/xorg-withfedy-mouseaccel.txt)
[xorg-withoutfedy-mouseaccel.txt](https://github.com/folkswithhats/fedy/files/1290559/xorg-withoutfedy-mouseaccel.txt)

Very strange phenomenon, took a while to debug because I thought it's a hardware issue.
Issue: with "disable mouse acceleration" script.

## Issue details

- When plugging in mice **while logged in,** they won't move the pointer. Click events are registered. Using "sudo libinput debug-events" shows the mouse movement events, so it works on a lower level.
- The same happens when resuming from suspend (which is a same as unplugging and plugging the mouse): the pointer is fixed at some location, won't move but clicks and scrolling is registered.
- Strangely, the pointer will work again after restarting the X server (e.g. with Ctrl-Alt-Backspace) and logging in again.

## Steps to reproduce

- Use Fedora 26 with GNOME 3.24.2. :)
- Enable the "disable mouse acceleration" plugin (mouse.plugin) in Fedy
- Restart the system
- Plug in a new mouse while being logged in or suspend and resume.

## Possible causes

I have absolutely no clue... please see the attached log files. The only different line is perhaps the Fedy Xorg.conf snippet being applied.

But it's 100% tested that this mouse script is the culprit! Is there any other log file that might be helpful for you?

**Comment by Abhinav1217** [comment]
We should also check if wayland has some role in causing this issue or not?

**Comment by gombosg** [comment]
Well, this is under Xorg. I'm not using Wayland, it's [too buggy](https://fedoraproject.org/wiki/Common_F26_bugs#Wayland_issues)... :)

**Comment by bddenhartog** [comment]
Removed myself - won't have time this week to investigate.

**Comment by agicquel** [comment]
I wrote the mouse acceleration script. It's just a well-known Xorg configuration in /etc/X11/xorg.conf.d/ It shouldn't cause any problem however you have to know Xorg have to be restarted after changes in conf to take effect. Maybe Xorg is guilty, that's strange.

**Comment by gombosg** [comment]
This bug seems to be gone in F27. Phew.

**Comment by bddenhartog** [comment]
Appears to be resolved.
