### ISSUE TITLE
[masterpdfeditor] URL is parsed but not assigned to variable

### ISSUE THREAD

**Issue by ArvindNair001** [folkswithhats/fedy#534]
https://github.com/folkswithhats/fedy/blob/596e484c739040616fd20c0c8675f1b23e80f257/plugins/masterpdfeditor.plugin/install.sh#L3

**Comment by bddenhartog** [comment]
Thanks -- good catch! 👍

**Comment by bddenhartog** [comment]
Huh - that's weird. The commit ID isn't referenced in the `close` action we see above. GitHub must not run merge commits made from the web interface through the same hooks.

This issue was closed in https://github.com/folkswithhats/fedy/commit/01251c9a8c18f5095690eab6d8e3ce72697a7142
