### ISSUE TITLE
What Gnome-Shell, GTK and Icon theme you use with Fedy screenshot? :)

### ISSUE THREAD

**Issue by Corsseir** [folkswithhats/fedy#538]
What Gnome-Shell, GTK and Icon theme you use in Fedy screenshot? :) I mean this one: https://www.folkswithhats.org/assets/fedy.png

Sry but I cant find other way to ask you about that.

**Comment by Abhinav1217** [comment]
These should be default themes. With a little touch-up done by @satya164.

**Comment by satya164** [comment]
It's Ozon GTK

**Comment by irondave** [comment]
@satya164 
I really loved the ozon themes, can we hope for new versions or the project has been abandoned definetively? I knew that the ozon linux distro was merged with korora long time ago, but since then nothing has been made known...

**Comment by bddenhartog** [comment]
Closing this issue, but please feel free to continue discussion.
