### ISSUE TITLE
Update Fedy?

### ISSUE THREAD

**Issue by beli3ver** [folkswithhats/fedy#549]
When will fedy be updated?

**Comment by bddenhartog** [comment]
Hey @beli3ver, thanks for the question. You can expect an update later today.

**Comment by bddenhartog** [comment]
Please try installing Fedy again. Targets have been built and deployed for Fedora 27 Stable. Please report any plugin-specific errors you may encounter in a new issue.

Sorry it took a few days, had some things come up.

**Comment by beli3ver** [comment]
Ok, when I take the this command on a new Fedora

`dnf -y install https://dl.folkswithhats.org/fedora/$(rpm -E %fedora)/RPMS/folkswithhats-release.noarch.rpm`

I installed the ***fedy*** Repo, but to install fedy, I musst install the RPM Fusion Free and Non-Free Repo frist, so the bash script before was better.

**Comment by bddenhartog** [comment]
> Ok, when I take the this command on a new Fedora
> 
> dnf -y install https://dl.folkswithhats.org/fedora/$(rpm -E %fedora)/RPMS/folkswithhats-release.noarch.rpm
> 
> I installed the fedy Repo, but to install fedy, I musst install the RPM Fusion Free and Non-Free Repo frist, so the bash script before was better.

Yeah, this is a downside to how a) the current packages are set up, and b) how the website is laid out. I'll be working on making the user experience much simpler and should hopefully have updates this weekend.
