### ISSUE TITLE
Fedy is not working with Fedora 27

### ISSUE THREAD

**Issue by ranjithsiji** [folkswithhats/fedy#550]
The current fedy is not working with Fedora 27. 

```
sudo sh -c 'curl https://www.folkswithhats.org/installer | bash' 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1171  100  1171    0     0   1171      0  0:00:01 --:--:--  0:00:01  2979
Last metadata expiration check: 0:28:15 ago on Tue 14 Nov 2017 11:34:33 PM IST.
[MIRROR] folkswithhats-release-3.0.0-1.noarch.rpm: Status code: 403 for https://dl.folkswithhats.org/fedora/27/RPMS/noarch/folkswithhats-release-3.0.0-1.noarch.rpm
[FAILED] folkswithhats-release-3.0.0-1.noarch.rpm: Status code: 403 for https://dl.folkswithhats.org/fedora/27/RPMS/noarch/folkswithhats-release-3.0.0-1.noarch.rpm
Status code: 403 for https://dl.folkswithhats.org/fedora/27/RPMS/noarch/folkswithhats-release-3.0.0-1.noarch.rpm
```

How can I install it for Fedora 27

**Comment by pscheid92** [comment]
Maybe this error is related to #543 ?

**Comment by bddenhartog** [comment]
Fedy is not yet built for F27. Expect a target later this week. I'll post on #543 when that has been done.

In the future, please ensure you a [searching the issues] before creating a new one, so that we can avoid duplicates like this. Thanks!

**Comment by ranjithsiji** [comment]
Sorry my bad. The issue was already there. And waiting for the F27 build.

**Comment by bddenhartog** [comment]
Please try installing Fedy again. Targets have been built and deployed for Fedora 27 Stable. Please report any plugin-specific errors you may encounter in a new issue.
