### ISSUE TITLE
Explain what it does and how it works

### ISSUE THREAD

**Issue by dAnjou** [folkswithhats/fedy#553]
... in README and on website.

There needs to be a good reason to install software without using the package manager. So if I do it I want to understand what's happening.

**Comment by bddenhartog** [comment]
Hey @dAnjou! Thanks for your idea. Did you have any specific ideas on what/where to improve? Here's how Fedy has been described for quite some time...

...from the [README](https://github.com/folkswithhats/fedy/tree/master/README.md):

> ### Introduction
> 
> Fedy lets you install multimedia codecs and additional software that Fedora doesn't want to ship, like mp3 support, Adobe Flash, Oracle Java etc., and much more with just a few clicks.

...from the [website](https://www.folkswithhats.org):

![](https://screenshots.firefoxusercontent.com/images/642e42d5-b713-45fe-b950-b20746c7f134.png)
![](https://screenshots.firefoxusercontent.com/images/7016bf6b-20d2-418c-8857-efddf4efdddf.png)

**Comment by dAnjou** [comment]
As a long time Linux user I've learned to trust the distros that I'm using and their package managers. I can rely on them and I know that they won't mess with my system. On the other hand I don't trust any other way of installing software, so I want to know what exactly it is doing to my system.

**Comment by danstewart** [comment]
@dAnjou 
We have this in the README:

> Each plugin is a directory with the suffix .plugin, which consist of a JSON formatted metadata file. The metadata file contains information about the plugin and describes how Fedy should run the tasks.

> The plugins can run any command or scripts (bash, python etc.). In addtion to the system commands, Fedy provides an additional command, run-as-root to allow running commands (e.g.- run-as-root touch /some/file/somewhere) or scripts (e.g.- run-as-root -s do-stuff.sh) as root.

The installation process is mostly bash scripts and `dnf`.
The whole point is to make installing software easier, for example here is the [install script for clion](https://github.com/folkswithhats/fedy/blob/master/plugins/clion.plugin/install.sh)

It's not very difficult to install yourself but clicking a button is easier.

What kind of information do you feel is missing and we can add it in?
Or what other questions do you have and we can answer them here?

**Comment by bddenhartog** [comment]
> As a long time Linux user I've learned to trust the distros that I'm using and their package managers. I can rely on them and I know that they won't mess with my system. On the other hand I don't trust any other way of installing software, so I want to know what exactly it is doing to my system.

In response to this, I would simply quote @danstewart:

> What kind of information do you feel is missing and we can add it in?
>  What other questions do you have and we can answer them here?

**Comment by danstewart** [comment]
Will close this due to the age of it and lack of discussion.
