### ISSUE TITLE
Issues with installations

### ISSUE THREAD

**Issue by kurosmael** [folkswithhats/fedy#555]
The repo (and website) appears to be down (or more precisely, forbidden by server) and when I exec 
`sudo dnf -y install https://dl.folkswithhats.org/fedora/$(rpm -E %fedora)/RPMS/folkswithhats-release.rpm `

I get 

> [MIRROR] folkswithhats-release.rpm: Status code: 403 for https://dl.folkswithhats.org/fedora/27/RPMS/folkswithhats-release.rpm
> [FAILED] folkswithhats-release.rpm: Status code: 403 for https://dl.folkswithhats.org/fedora/27/RPMS/folkswithhats-release.rpm
> Status code: 403 for https://dl.folkswithhats.org/fedora/27/RPMS/folkswithhats-release.rpm

And even if I've tested it on fedora 27 here, it's the same from fedora 26 on VMs.

**Comment by danstewart** [comment]
You have a typo in your command

https://dl.folkswithhats.org/fedora/$(rpm -E %fedora)/RPMS/folkswithhats-release.noarch.rpm
