### ISSUE TITLE
Fedy home webpage has bad install instructions

### ISSUE THREAD

**Issue by valentt** [folkswithhats/fedy#569]
If you copy/paste instructions from Fedy web page you don't end up with Fedy tool installed.

This is strange, because previously instructions on Fedy web page were useful and now they are very confusing, especially for new users.

**Comment by DevPre** [comment]
```
su
dnf install https://dl.folkswithhats.org/fedora/$(rpm -E %fedora)/RPMS/folkswithhats-release.noarch.rpm
dnf update
dnf install fedy
```

The instructions on the website are partial.

**Comment by GabLeRoux** [comment]
Can probably be closed by folkswithhats/folkswithhats.org@e911a05 👍

**Comment by bddenhartog** [comment]
@GabLeRoux Good catch.
