### ISSUE TITLE
Brackets installation failed

### ISSUE THREAD

**Issue by sam0hack** [folkswithhats/fedy#574]
I'm using Fedora 27 and fedy is unable to install brackets

**Comment by bddenhartog** [comment]
Please do the following:

1. From a terminal, type `fedy | tee /tmp/fedy-brackets.log` and press enter.
2. Without doing anything else, attempt to install the Brackets plugin. After it fails, close the Fedy application.
3. Paste the output of `/tmp/fedy-brackets.log` here. If you have xclip installed, you can run `cat /tmp/fedy-brackets.log | xclip -selection clipboard` to copy the contents directly to your clipboard.

The Brackets plugin simply interfaces with COPR by enabling the [`mosquito/brackets` COPR][0] and installing the package. More than likely, the reponse to your follow-up report will be to file an issue [with the `FZUG/repo` project][1], but it's possible you're running into something else.

[0]: https://copr.fedorainfracloud.org/coprs/mosquito/brackets/
[1]: https://github.com/FZUG/repo

**Comment by bddenhartog** [comment]
@sam0hack , did you figure out the cause and solution for your issue?

**Comment by bddenhartog** [comment]
@sam0hack , did you figure out the cause and solution for your issue? Leaving a comment for both my and future readers' knowledge would be greatly appreciated.

**Comment by bddenhartog** [comment]
I figured as much - just wanted to make sure we didn't leave this story unanswered.

I'll create an issue to find and implement a new source for Brackets, or to remove it if no suitable source is found.

**Comment by sam0hack** [comment]
Great. and @bddenhartog thank you for making this wonderful tool. I'll look forward to contributing to this repository.
