### ISSUE TITLE
BitTorrent Sync (btsync)

### ISSUE THREAD

**Issue by kaveiros** [folkswithhats/fedy#94]
Could you please consider adding the installation option for btsync ? just a little script that will allow newbies set their password, port for btsync, and add it to systemd without having to "dig" through config files so it will run at startup easily. Thank you in advance.

**Comment by satya164** [comment]
I've been busy lately. So if someone could send a pull request, it'll be great.

**Comment by Rohan62442** [comment]
I'm working on this...

**Comment by Rohan62442** [comment]
I'm having a problem however. It's recommended that btsync not be installed as root, but fedy itself runs with root privileges. So it is a problem. Also, it gives a permission denied error when btsync (installed by fedy) is run... Any help?

**Comment by satya164** [comment]
Can you point me to the branch? I'll investigate.

**Comment by Rohan62442** [comment]
Here -> https://github.com/Rohan62442/fedy/tree/bittorrent-sync

**Comment by satya164** [comment]
@Rohan62442 Any updates on this? I would be great if you could redo the plugin according to the new structure before I release the next version of Fedy.

**Comment by user501254** [comment]
Done in Commit d57ce5ee512bf2db553001175b2a7d46ffd02088.
